import typing
from System import Attribute

class AssemblyIpcProxyAttribute(Attribute):
    def __init__(self, contractType: typing.Type[typing.Any], ipcType: typing.Type[typing.Any], proxyType: typing.Type[typing.Any]) -> None: ...
    @property
    def ContractType(self) -> typing.Type[typing.Any]: ...
    @property
    def IpcType(self) -> typing.Type[typing.Any]: ...
    @IpcType.setter
    def IpcType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ProxyType(self) -> typing.Type[typing.Any]: ...
    @ProxyType.setter
    def ProxyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def TypeId(self) -> typing.Any: ...


class AssemblyIpcProxyJointAttribute(Attribute):
    def __init__(self, ipcType: typing.Type[typing.Any], proxyType: typing.Type[typing.Any], jointType: typing.Type[typing.Any]) -> None: ...
    @property
    def IpcType(self) -> typing.Type[typing.Any]: ...
    @IpcType.setter
    def IpcType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def JointType(self) -> typing.Type[typing.Any]: ...
    @JointType.setter
    def JointType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ProxyType(self) -> typing.Type[typing.Any]: ...
    @ProxyType.setter
    def ProxyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def TypeId(self) -> typing.Any: ...


class IpcEventAttribute(IpcMemberAttribute):
    def __init__(self) -> None: ...
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...


class IpcMemberAttribute(Attribute):
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...


class IpcMethodAttribute(IpcMemberAttribute):
    def __init__(self) -> None: ...
    @property
    def DefaultReturn(self) -> typing.Any: ...
    @DefaultReturn.setter
    def DefaultReturn(self, value: typing.Any) -> typing.Any: ...
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...
    @property
    def WaitsVoid(self) -> bool: ...
    @WaitsVoid.setter
    def WaitsVoid(self, value: bool) -> bool: ...


class IpcPropertyAttribute(IpcMemberAttribute):
    def __init__(self) -> None: ...
    @property
    def DefaultReturn(self) -> typing.Any: ...
    @DefaultReturn.setter
    def DefaultReturn(self, value: typing.Any) -> typing.Any: ...
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def IsReadonly(self) -> bool: ...
    @IsReadonly.setter
    def IsReadonly(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...


class IpcPublicAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...


class IpcShapeAttribute(IpcPublicAttribute):
    def __init__(self, contractType: typing.Type[typing.Any]) -> None: ...
    @property
    def ContractType(self) -> typing.Type[typing.Any]: ...
    @property
    def IgnoresIpcException(self) -> bool: ...
    @IgnoresIpcException.setter
    def IgnoresIpcException(self, value: bool) -> bool: ...
    @property
    def Timeout(self) -> int: ...
    @Timeout.setter
    def Timeout(self, value: int) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...

