import typing, abc
from System import Attribute, Array_1
from System.ComponentModel import INotifyPropertyChanging, INotifyPropertyChanged, INotifyDataErrorInfo
from System.Collections.Generic import IEnumerable_1
from System.ComponentModel.DataAnnotations import ValidationResult

class INotifyPropertyChangedAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def IncludeAdditionalHelperMethods(self) -> bool: ...
    @IncludeAdditionalHelperMethods.setter
    def IncludeAdditionalHelperMethods(self, value: bool) -> bool: ...
    @property
    def TypeId(self) -> typing.Any: ...


class NotifyCanExecuteChangedForAttribute(Attribute):
    @typing.overload
    def __init__(self, commandName: str) -> None: ...
    @typing.overload
    def __init__(self, commandName: str, otherCommandNames: Array_1[str]) -> None: ...
    @property
    def CommandNames(self) -> Array_1[str]: ...
    @property
    def TypeId(self) -> typing.Any: ...


class NotifyDataErrorInfoAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class NotifyPropertyChangedForAttribute(Attribute):
    @typing.overload
    def __init__(self, propertyName: str) -> None: ...
    @typing.overload
    def __init__(self, propertyName: str, otherPropertyNames: Array_1[str]) -> None: ...
    @property
    def PropertyNames(self) -> Array_1[str]: ...
    @property
    def TypeId(self) -> typing.Any: ...


class NotifyPropertyChangedRecipientsAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class ObservableObject(INotifyPropertyChanging, INotifyPropertyChanged, abc.ABC):
    pass


class ObservableObjectAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class ObservablePropertyAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class ObservableRecipient(ObservableObject):
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...


class ObservableRecipientAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class ObservableValidator(ObservableObject, INotifyDataErrorInfo):
    @property
    def HasErrors(self) -> bool: ...
    def GetErrors(self, propertyName: str = ...) -> IEnumerable_1[ValidationResult]: ...

