from dotnetCampus.Ipc.Messages import IpcMessageBody
from System import Exception, Array_1

class ReceiveMessageBodyLogState:
    def __init__(self, ipcMessageBody: IpcMessageBody, localPeerName: str, remotePeerName: str, isBusinessMessage: bool) -> None: ...
    @property
    def IpcMessageBody(self) -> IpcMessageBody: ...
    @property
    def IsBusinessMessage(self) -> bool: ...
    @property
    def LocalPeerName(self) -> str: ...
    @property
    def RemotePeerName(self) -> str: ...
    @staticmethod
    def Format(state: ReceiveMessageBodyLogState, exception: Exception) -> str: ...
    def FormatAsBinary(self) -> str: ...
    def FormatAsText(self) -> str: ...


class SendMessageBodiesLogState:
    @property
    def IpcBufferMessageList(self) -> Array_1[IpcMessageBody]: ...
    @property
    def LocalPeerName(self) -> str: ...
    @property
    def RemotePeerName(self) -> str: ...
    @staticmethod
    def Format(state: SendMessageBodiesLogState, exception: Exception) -> str: ...
    def FormatAsBinary(self) -> str: ...
    def FormatAsText(self) -> str: ...


class SendMessageBodyLogState:
    def __init__(self, ipcMessageBody: IpcMessageBody, localPeerName: str, remotePeerName: str) -> None: ...
    @property
    def IpcMessageBody(self) -> IpcMessageBody: ...
    @property
    def LocalPeerName(self) -> str: ...
    @property
    def RemotePeerName(self) -> str: ...
    @staticmethod
    def Format(state: SendMessageBodyLogState, exception: Exception) -> str: ...
    def FormatAsBinary(self) -> str: ...
    def FormatAsText(self) -> str: ...

