import typing
from ClassIsland.Shared import AttachableSettingsObject
from System.Collections.Generic import Dictionary_2
from System import Guid, DateTime, IComparable, TimeSpan
from System.Collections.ObjectModel import ObservableCollection_1
from CommunityToolkit.Mvvm.ComponentModel import ObservableRecipient
from ClassIsland.Shared.ComponentModels import ObservableDictionary_2
from ClassIsland.Shared.Enums import TempClassPlanGroupType
from ClassIsland.Shared.Models.Automation import ActionSet

class ClassInfo(AttachableSettingsObject):
    def __init__(self) -> None: ...
    @property
    def AttachedObjects(self) -> Dictionary_2[Guid, typing.Any]: ...
    @AttachedObjects.setter
    def AttachedObjects(self, value: Dictionary_2[Guid, typing.Any]) -> Dictionary_2[Guid, typing.Any]: ...
    @property
    def CurrentTimeLayout(self) -> TimeLayout: ...
    @CurrentTimeLayout.setter
    def CurrentTimeLayout(self, value: TimeLayout) -> TimeLayout: ...
    @property
    def CurrentTimeLayoutItem(self) -> TimeLayoutItem: ...
    @property
    def Index(self) -> int: ...
    @Index.setter
    def Index(self, value: int) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsChangedClass(self) -> bool: ...
    @IsChangedClass.setter
    def IsChangedClass(self, value: bool) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def SubjectId(self) -> Guid: ...
    @SubjectId.setter
    def SubjectId(self, value: Guid) -> Guid: ...


class ClassPlan(AttachableSettingsObject):
    def __init__(self) -> None: ...
    @property
    def AssociatedGroup(self) -> Guid: ...
    @AssociatedGroup.setter
    def AssociatedGroup(self, value: Guid) -> Guid: ...
    @property
    def AttachedObjects(self) -> Dictionary_2[Guid, typing.Any]: ...
    @AttachedObjects.setter
    def AttachedObjects(self, value: Dictionary_2[Guid, typing.Any]) -> Dictionary_2[Guid, typing.Any]: ...
    @property
    def Classes(self) -> ObservableCollection_1[ClassInfo]: ...
    @Classes.setter
    def Classes(self, value: ObservableCollection_1[ClassInfo]) -> ObservableCollection_1[ClassInfo]: ...
    @property
    def IsActivated(self) -> bool: ...
    @IsActivated.setter
    def IsActivated(self, value: bool) -> bool: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsOverlay(self) -> bool: ...
    @IsOverlay.setter
    def IsOverlay(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def OverlaySetupTime(self) -> DateTime: ...
    @OverlaySetupTime.setter
    def OverlaySetupTime(self, value: DateTime) -> DateTime: ...
    @property
    def OverlaySourceId(self) -> typing.Optional[Guid]: ...
    @OverlaySourceId.setter
    def OverlaySourceId(self, value: typing.Optional[Guid]) -> typing.Optional[Guid]: ...
    @property
    def TimeLayout(self) -> TimeLayout: ...
    @property
    def TimeLayoutId(self) -> Guid: ...
    @TimeLayoutId.setter
    def TimeLayoutId(self, value: Guid) -> Guid: ...
    @property
    def TimeRule(self) -> TimeRule: ...
    @TimeRule.setter
    def TimeRule(self, value: TimeRule) -> TimeRule: ...
    @property
    def ValidTimeLayoutItems(self) -> ObservableCollection_1[TimeLayoutItem]: ...


class ClassPlanGroup(ObservableRecipient):
    def __init__(self) -> None: ...
    @classmethod
    @property
    def DefaultGroupGuid(cls) -> Guid: ...
    @classmethod
    @property
    def GlobalGroupGuid(cls) -> Guid: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsGlobal(self) -> bool: ...
    @IsGlobal.setter
    def IsGlobal(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...


class OrderedSchedule(ObservableRecipient):
    def __init__(self) -> None: ...
    @property
    def ClassPlanId(self) -> Guid: ...
    @ClassPlanId.setter
    def ClassPlanId(self, value: Guid) -> Guid: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...


class Profile(ObservableRecipient):
    def __init__(self) -> None: ...
    @property
    def ClassPlanGroups(self) -> ObservableDictionary_2[Guid, ClassPlanGroup]: ...
    @ClassPlanGroups.setter
    def ClassPlanGroups(self, value: ObservableDictionary_2[Guid, ClassPlanGroup]) -> ObservableDictionary_2[Guid, ClassPlanGroup]: ...
    @property
    def ClassPlans(self) -> ObservableDictionary_2[Guid, ClassPlan]: ...
    @ClassPlans.setter
    def ClassPlans(self, value: ObservableDictionary_2[Guid, ClassPlan]) -> ObservableDictionary_2[Guid, ClassPlan]: ...
    @property
    def EditingSubjects(self) -> ObservableCollection_1[Subject]: ...
    @EditingSubjects.setter
    def EditingSubjects(self, value: ObservableCollection_1[Subject]) -> ObservableCollection_1[Subject]: ...
    @property
    def HasOverlayClassPlan(self) -> bool: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsOverlayClassPlanEnabled(self) -> bool: ...
    @IsOverlayClassPlanEnabled.setter
    def IsOverlayClassPlanEnabled(self, value: bool) -> bool: ...
    @property
    def IsTempClassPlanGroupEnabled(self) -> bool: ...
    @IsTempClassPlanGroupEnabled.setter
    def IsTempClassPlanGroupEnabled(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def OrderedSchedules(self) -> ObservableDictionary_2[DateTime, OrderedSchedule]: ...
    @OrderedSchedules.setter
    def OrderedSchedules(self, value: ObservableDictionary_2[DateTime, OrderedSchedule]) -> ObservableDictionary_2[DateTime, OrderedSchedule]: ...
    @property
    def OverlayClassPlanId(self) -> typing.Optional[Guid]: ...
    @OverlayClassPlanId.setter
    def OverlayClassPlanId(self, value: typing.Optional[Guid]) -> typing.Optional[Guid]: ...
    @property
    def SelectedClassPlanGroupId(self) -> Guid: ...
    @SelectedClassPlanGroupId.setter
    def SelectedClassPlanGroupId(self, value: Guid) -> Guid: ...
    @property
    def Subjects(self) -> ObservableDictionary_2[Guid, Subject]: ...
    @Subjects.setter
    def Subjects(self, value: ObservableDictionary_2[Guid, Subject]) -> ObservableDictionary_2[Guid, Subject]: ...
    @property
    def TempClassPlanGroupExpireTime(self) -> DateTime: ...
    @TempClassPlanGroupExpireTime.setter
    def TempClassPlanGroupExpireTime(self, value: DateTime) -> DateTime: ...
    @property
    def TempClassPlanGroupId(self) -> typing.Optional[Guid]: ...
    @TempClassPlanGroupId.setter
    def TempClassPlanGroupId(self, value: typing.Optional[Guid]) -> typing.Optional[Guid]: ...
    @property
    def TempClassPlanGroupType(self) -> TempClassPlanGroupType: ...
    @TempClassPlanGroupType.setter
    def TempClassPlanGroupType(self, value: TempClassPlanGroupType) -> TempClassPlanGroupType: ...
    @property
    def TempClassPlanId(self) -> typing.Optional[Guid]: ...
    @TempClassPlanId.setter
    def TempClassPlanId(self, value: typing.Optional[Guid]) -> typing.Optional[Guid]: ...
    @property
    def TempClassPlanSetupTime(self) -> DateTime: ...
    @TempClassPlanSetupTime.setter
    def TempClassPlanSetupTime(self, value: DateTime) -> DateTime: ...
    @property
    def TimeLayouts(self) -> ObservableDictionary_2[Guid, TimeLayout]: ...
    @TimeLayouts.setter
    def TimeLayouts(self, value: ObservableDictionary_2[Guid, TimeLayout]) -> ObservableDictionary_2[Guid, TimeLayout]: ...
    def DeleteClassPlanGroup(self, id: Guid) -> None: ...
    def DisbandClassPlanGroup(self, id: Guid) -> None: ...
    def OverwriteAllClassPlanSubject(self, timeLayoutId: Guid, timePoint: TimeLayoutItem, subjectId: Guid) -> None: ...


class Subject(AttachableSettingsObject):
    def __init__(self) -> None: ...
    Breaking : Subject
    Empty : Subject
    Fallback : Subject
    @property
    def AttachedObjects(self) -> Dictionary_2[Guid, typing.Any]: ...
    @AttachedObjects.setter
    def AttachedObjects(self, value: Dictionary_2[Guid, typing.Any]) -> Dictionary_2[Guid, typing.Any]: ...
    @property
    def Initial(self) -> str: ...
    @Initial.setter
    def Initial(self, value: str) -> str: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsOutDoor(self) -> bool: ...
    @IsOutDoor.setter
    def IsOutDoor(self, value: bool) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def TeacherName(self) -> str: ...
    @TeacherName.setter
    def TeacherName(self, value: str) -> str: ...
    def GetFirstName(self) -> str: ...


class TimeLayout(AttachableSettingsObject):
    def __init__(self) -> None: ...
    @property
    def AttachedObjects(self) -> Dictionary_2[Guid, typing.Any]: ...
    @AttachedObjects.setter
    def AttachedObjects(self, value: Dictionary_2[Guid, typing.Any]) -> Dictionary_2[Guid, typing.Any]: ...
    @property
    def IsActivated(self) -> bool: ...
    @IsActivated.setter
    def IsActivated(self, value: bool) -> bool: ...
    @property
    def IsActivatedManually(self) -> bool: ...
    @IsActivatedManually.setter
    def IsActivatedManually(self, value: bool) -> bool: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def Layouts(self) -> ObservableCollection_1[TimeLayoutItem]: ...
    @Layouts.setter
    def Layouts(self, value: ObservableCollection_1[TimeLayoutItem]) -> ObservableCollection_1[TimeLayoutItem]: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    def InsertTimePoint(self, index: int, item: TimeLayoutItem) -> None: ...
    def RemoveTimePoint(self, item: TimeLayoutItem) -> None: ...


class TimeLayoutItem(AttachableSettingsObject, IComparable):
    def __init__(self) -> None: ...
    Empty : TimeLayoutItem
    @property
    def ActionSet(self) -> ActionSet: ...
    @ActionSet.setter
    def ActionSet(self, value: ActionSet) -> ActionSet: ...
    @property
    def AttachedObjects(self) -> Dictionary_2[Guid, typing.Any]: ...
    @AttachedObjects.setter
    def AttachedObjects(self, value: Dictionary_2[Guid, typing.Any]) -> Dictionary_2[Guid, typing.Any]: ...
    @property
    def BreakName(self) -> str: ...
    @BreakName.setter
    def BreakName(self, value: str) -> str: ...
    @property
    def BreakNameText(self) -> str: ...
    @property
    def DefaultClassId(self) -> Guid: ...
    @DefaultClassId.setter
    def DefaultClassId(self, value: Guid) -> Guid: ...
    @property
    def EndSecond(self) -> str: ...
    @EndSecond.setter
    def EndSecond(self, value: str) -> str: ...
    @property
    def EndTime(self) -> TimeSpan: ...
    @EndTime.setter
    def EndTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsHideDefault(self) -> bool: ...
    @IsHideDefault.setter
    def IsHideDefault(self, value: bool) -> bool: ...
    @property
    def Last(self) -> TimeSpan: ...
    @property
    def StartSecond(self) -> str: ...
    @StartSecond.setter
    def StartSecond(self, value: str) -> str: ...
    @property
    def StartTime(self) -> TimeSpan: ...
    @StartTime.setter
    def StartTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def TimeType(self) -> int: ...
    @TimeType.setter
    def TimeType(self, value: int) -> int: ...
    def CompareTo(self, obj: typing.Any) -> int: ...
    def ToString(self) -> str: ...


class TimeRule(ObservableRecipient):
    def __init__(self) -> None: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def WeekCountDiv(self) -> int: ...
    @WeekCountDiv.setter
    def WeekCountDiv(self, value: int) -> int: ...
    @property
    def WeekCountDivTotal(self) -> int: ...
    @WeekCountDivTotal.setter
    def WeekCountDivTotal(self, value: int) -> int: ...
    @property
    def WeekDay(self) -> int: ...
    @WeekDay.setter
    def WeekDay(self, value: int) -> int: ...

