import typing
from CommunityToolkit.Mvvm.ComponentModel import ObservableRecipient
from System.Collections.ObjectModel import ObservableCollection_1
from System import Guid
from ClassIsland.Shared.Enums import ActionSetStatus

class ActionItem(ObservableRecipient):
    def __init__(self) -> None: ...
    @property
    def Exception(self) -> str: ...
    @Exception.setter
    def Exception(self, value: str) -> str: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> str: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsCompleted(self) -> bool: ...
    @IsCompleted.setter
    def IsCompleted(self, value: bool) -> bool: ...
    @property
    def IsRevertActionItem(self) -> bool: ...
    @IsRevertActionItem.setter
    def IsRevertActionItem(self, value: bool) -> bool: ...
    @property
    def IsRevertEnabled(self) -> bool: ...
    @IsRevertEnabled.setter
    def IsRevertEnabled(self, value: bool) -> bool: ...
    @property
    def IsWorking(self) -> bool: ...
    @IsWorking.setter
    def IsWorking(self, value: bool) -> bool: ...
    @property
    def Progress(self) -> typing.Optional[float]: ...
    @Progress.setter
    def Progress(self, value: typing.Optional[float]) -> typing.Optional[float]: ...
    @property
    def Settings(self) -> typing.Any: ...
    @Settings.setter
    def Settings(self, value: typing.Any) -> typing.Any: ...
    def SetEndRunning(self) -> None: ...
    def SetStartRunning(self) -> None: ...


class ActionSet(ObservableRecipient):
    def __init__(self) -> None: ...
    @property
    def ActionItems(self) -> ObservableCollection_1[ActionItem]: ...
    @ActionItems.setter
    def ActionItems(self, value: ObservableCollection_1[ActionItem]) -> ObservableCollection_1[ActionItem]: ...
    @property
    def Guid(self) -> Guid: ...
    @Guid.setter
    def Guid(self, value: Guid) -> Guid: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsRevertEnabled(self) -> bool: ...
    @IsRevertEnabled.setter
    def IsRevertEnabled(self, value: bool) -> bool: ...
    @property
    def IsWorking(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Status(self) -> ActionSetStatus: ...
    @Status.setter
    def Status(self, value: ActionSetStatus) -> ActionSetStatus: ...
    def SetEndRunning(self, isInvoke: bool) -> None: ...
    def SetStartRunning(self, isInvoke: bool) -> None: ...

