import typing, clr, abc
from System.Collections.Generic import IReadOnlyDictionary_2, IDictionary_2, IEqualityComparer_1, ICollection_1, KeyValuePair_2, IEnumerator_1
from System.Collections import IDictionary
from System.ComponentModel import INotifyPropertyChanged
from System.Collections.Specialized import INotifyCollectionChanged
from System import Array_1

class ObservableDictionary_GenericClasses(abc.ABCMeta):
    Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TKey = typing.TypeVar('Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TKey')
    Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TValue = typing.TypeVar('Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TValue')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TKey], typing.Type[Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TValue]]) -> typing.Type[ObservableDictionary_2[Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TKey, Generic_ObservableDictionary_GenericClasses_ObservableDictionary_2_TValue]]: ...

ObservableDictionary : ObservableDictionary_GenericClasses

ObservableDictionary_2_TKey = typing.TypeVar('ObservableDictionary_2_TKey')
ObservableDictionary_2_TValue = typing.TypeVar('ObservableDictionary_2_TValue')
class ObservableDictionary_2(typing.Generic[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue], IReadOnlyDictionary_2[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue], IDictionary_2[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue], IDictionary, INotifyPropertyChanged, INotifyCollectionChanged):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int) -> None: ...
    @typing.overload
    def __init__(self, dictionary: IDictionary_2[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue], comparer: IEqualityComparer_1[ObservableDictionary_2_TKey] = ...) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def Item(self) -> ObservableDictionary_2_TValue: ...
    @Item.setter
    def Item(self, value: ObservableDictionary_2_TValue) -> ObservableDictionary_2_TValue: ...
    @property
    def Keys(self) -> ICollection_1[ObservableDictionary_2_TKey]: ...
    @property
    def Values(self) -> ICollection_1[ObservableDictionary_2_TValue]: ...
    def Add(self, key: ObservableDictionary_2_TKey, value: ObservableDictionary_2_TValue) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: ObservableDictionary_2_TKey) -> bool: ...
    def CopyTo(self, array: Array_1[KeyValuePair_2[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue]], arrayIndex: int) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[KeyValuePair_2[ObservableDictionary_2_TKey, ObservableDictionary_2_TValue]]: ...
    def Remove(self, key: ObservableDictionary_2_TKey) -> bool: ...
    def TryGetValue(self, key: ObservableDictionary_2_TKey, value: clr.Reference[ObservableDictionary_2_TValue]) -> bool: ...

