import typing
from System import Array_1, DateTimeKind, Decimal, DateTime, DateTimeOffset, Guid, TimeSpan, Uri
from Newtonsoft.Json import JsonReader, DateParseHandling, DateTimeZoneHandling, FloatParseHandling, JsonToken, JsonWriter, DateFormatHandling, FloatFormatHandling, Formatting, StringEscapeHandling, WriteState
from System.IO import BinaryReader, Stream, BinaryWriter
from System.Globalization import CultureInfo

class BsonObjectId:
    def __init__(self, value: Array_1[int]) -> None: ...
    @property
    def Value(self) -> Array_1[int]: ...


class BsonReader(JsonReader):
    @typing.overload
    def __init__(self, reader: BinaryReader) -> None: ...
    @typing.overload
    def __init__(self, reader: BinaryReader, readRootValueAsArray: bool, dateTimeKindHandling: DateTimeKind) -> None: ...
    @typing.overload
    def __init__(self, stream: Stream) -> None: ...
    @typing.overload
    def __init__(self, stream: Stream, readRootValueAsArray: bool, dateTimeKindHandling: DateTimeKind) -> None: ...
    @property
    def CloseInput(self) -> bool: ...
    @CloseInput.setter
    def CloseInput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeKindHandling(self) -> DateTimeKind: ...
    @DateTimeKindHandling.setter
    def DateTimeKindHandling(self, value: DateTimeKind) -> DateTimeKind: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def Depth(self) -> int: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def JsonNet35BinaryCompatibility(self) -> bool: ...
    @JsonNet35BinaryCompatibility.setter
    def JsonNet35BinaryCompatibility(self, value: bool) -> bool: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def Path(self) -> str: ...
    @property
    def QuoteChar(self) -> str: ...
    @QuoteChar.setter
    def QuoteChar(self, value: str) -> str: ...
    @property
    def ReadRootValueAsArray(self) -> bool: ...
    @ReadRootValueAsArray.setter
    def ReadRootValueAsArray(self, value: bool) -> bool: ...
    @property
    def SupportMultipleContent(self) -> bool: ...
    @SupportMultipleContent.setter
    def SupportMultipleContent(self, value: bool) -> bool: ...
    @property
    def TokenType(self) -> JsonToken: ...
    @property
    def Value(self) -> typing.Any: ...
    @property
    def ValueType(self) -> typing.Type[typing.Any]: ...
    def Close(self) -> None: ...
    def Read(self) -> bool: ...


class BsonWriter(JsonWriter):
    @typing.overload
    def __init__(self, stream: Stream) -> None: ...
    @typing.overload
    def __init__(self, writer: BinaryWriter) -> None: ...
    @property
    def AutoCompleteOnClose(self) -> bool: ...
    @AutoCompleteOnClose.setter
    def AutoCompleteOnClose(self, value: bool) -> bool: ...
    @property
    def CloseOutput(self) -> bool: ...
    @CloseOutput.setter
    def CloseOutput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatHandling(self) -> DateFormatHandling: ...
    @DateFormatHandling.setter
    def DateFormatHandling(self, value: DateFormatHandling) -> DateFormatHandling: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateTimeKindHandling(self) -> DateTimeKind: ...
    @DateTimeKindHandling.setter
    def DateTimeKindHandling(self, value: DateTimeKind) -> DateTimeKind: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def FloatFormatHandling(self) -> FloatFormatHandling: ...
    @FloatFormatHandling.setter
    def FloatFormatHandling(self, value: FloatFormatHandling) -> FloatFormatHandling: ...
    @property
    def Formatting(self) -> Formatting: ...
    @Formatting.setter
    def Formatting(self, value: Formatting) -> Formatting: ...
    @property
    def Path(self) -> str: ...
    @property
    def StringEscapeHandling(self) -> StringEscapeHandling: ...
    @StringEscapeHandling.setter
    def StringEscapeHandling(self, value: StringEscapeHandling) -> StringEscapeHandling: ...
    @property
    def WriteState(self) -> WriteState: ...
    def Close(self) -> None: ...
    def Flush(self) -> None: ...
    def WriteComment(self, text: str) -> None: ...
    def WriteNull(self) -> None: ...
    def WriteObjectId(self, value: Array_1[int]) -> None: ...
    def WritePropertyName(self, name: str) -> None: ...
    def WriteRaw(self, json: str) -> None: ...
    def WriteRawValue(self, json: str) -> None: ...
    def WriteRegex(self, pattern: str, options: str) -> None: ...
    def WriteStartArray(self) -> None: ...
    def WriteStartConstructor(self, name: str) -> None: ...
    def WriteStartObject(self) -> None: ...
    def WriteUndefined(self) -> None: ...
    # Skipped WriteValue due to it being static, abstract and generic.

    WriteValue : WriteValue_MethodGroup
    class WriteValue_MethodGroup:
        @typing.overload
        def __call__(self, value: float) -> None:...
        # Method WriteValue(value : Double) was skipped since it collides with above method
        # Method WriteValue(value : Int32) was skipped since it collides with above method
        # Method WriteValue(value : UInt32) was skipped since it collides with above method
        # Method WriteValue(value : Int64) was skipped since it collides with above method
        # Method WriteValue(value : UInt64) was skipped since it collides with above method
        # Method WriteValue(value : Int16) was skipped since it collides with above method
        # Method WriteValue(value : UInt16) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str) -> None:...
        # Method WriteValue(value : Byte) was skipped since it collides with above method
        # Method WriteValue(value : SByte) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[int]) -> None:...
        # Method WriteValue(value : String) was skipped since it collides with above method
        # Method WriteValue(value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: DateTime) -> None:...
        @typing.overload
        def __call__(self, value: DateTimeOffset) -> None:...
        @typing.overload
        def __call__(self, value: Guid) -> None:...
        @typing.overload
        def __call__(self, value: TimeSpan) -> None:...
        @typing.overload
        def __call__(self, value: Uri) -> None:...
        @typing.overload
        def __call__(self, value: typing.Any) -> None:...


