import typing
from System import IDisposable, Array_1
from dotnetCampus.Ipc.Context import IpcContext, IpcConfiguration
from System.Threading.Tasks import Task, Task_1
from dotnetCampus.Ipc import IIpcProvider, IPeerProxy
from dotnetCampus.Ipc.Messages import IpcMessage

class IpcClientService(IDisposable):
    @property
    def IpcContext(self) -> IpcContext: ...
    @property
    def PeerName(self) -> str: ...
    def Dispose(self) -> None: ...
    def Start(self, shouldRegisterToPeer: bool = ...) -> Task: ...
    def Stop(self) -> None: ...
    def WriteMessageAsync(self, buffer: Array_1[int], offset: int, count: int, tag: str = ...) -> Task: ...


class IpcProvider(IDisposable, IIpcProvider):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, pipeName: str, ipcConfiguration: IpcConfiguration = ...) -> None: ...
    @property
    def IpcContext(self) -> IpcContext: ...
    @property
    def IpcServerService(self) -> IpcServerService: ...
    @property
    def IsStarted(self) -> bool: ...
    def Dispose(self) -> None: ...
    def GetAndConnectToPeerAsync(self, peerName: str) -> Task_1[PeerProxy]: ...
    def StartServer(self) -> None: ...


class IpcServerService(IDisposable):
    def __init__(self, ipcContext: IpcContext) -> None: ...
    @property
    def IpcContext(self) -> IpcContext: ...
    def Dispose(self) -> None: ...
    def Start(self) -> Task: ...


class PeerProxy(IPeerProxy):
    @property
    def IsConnectedFinished(self) -> bool: ...
    @IsConnectedFinished.setter
    def IsConnectedFinished(self, value: bool) -> bool: ...
    @property
    def PeerName(self) -> str: ...
    def GetResponseAsync(self, request: IpcMessage) -> Task_1[IpcMessage]: ...
    def NotifyAsync(self, request: IpcMessage) -> Task: ...

