import typing, clr, abc
from System.Reflection import BindingFlags, MemberInfo, MethodInfo
from System.Runtime.Serialization import SerializationBinder, StreamingContext
from System.Diagnostics import TraceLevel
from System import Exception, EventArgs, MulticastDelegate, IAsyncResult, AsyncCallback, Attribute, Func_1, Func_2, Predicate_1, Action_2, StringComparison, Array_1
from System.Collections.Generic import IEnumerable_1, KeyValuePair_2, IList_1, IEqualityComparer_1
from Newtonsoft.Json import JsonConverter, ReferenceLoopHandling, TypeNameHandling, NullValueHandling, Required, MemberSerialization, MissingMemberHandling, DefaultValueHandling, ObjectCreationHandling
from System.Collections.ObjectModel import KeyedCollection_2

class CamelCaseNamingStrategy(NamingStrategy):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool, processExtensionDataNames: bool) -> None: ...
    @property
    def OverrideSpecifiedNames(self) -> bool: ...
    @OverrideSpecifiedNames.setter
    def OverrideSpecifiedNames(self, value: bool) -> bool: ...
    @property
    def ProcessDictionaryKeys(self) -> bool: ...
    @ProcessDictionaryKeys.setter
    def ProcessDictionaryKeys(self, value: bool) -> bool: ...
    @property
    def ProcessExtensionDataNames(self) -> bool: ...
    @ProcessExtensionDataNames.setter
    def ProcessExtensionDataNames(self, value: bool) -> bool: ...


class CamelCasePropertyNamesContractResolver(DefaultContractResolver):
    def __init__(self) -> None: ...
    @property
    def DefaultMembersSearchFlags(self) -> BindingFlags: ...
    @DefaultMembersSearchFlags.setter
    def DefaultMembersSearchFlags(self, value: BindingFlags) -> BindingFlags: ...
    @property
    def DynamicCodeGeneration(self) -> bool: ...
    @property
    def IgnoreIsSpecifiedMembers(self) -> bool: ...
    @IgnoreIsSpecifiedMembers.setter
    def IgnoreIsSpecifiedMembers(self, value: bool) -> bool: ...
    @property
    def IgnoreSerializableAttribute(self) -> bool: ...
    @IgnoreSerializableAttribute.setter
    def IgnoreSerializableAttribute(self, value: bool) -> bool: ...
    @property
    def IgnoreSerializableInterface(self) -> bool: ...
    @IgnoreSerializableInterface.setter
    def IgnoreSerializableInterface(self, value: bool) -> bool: ...
    @property
    def IgnoreShouldSerializeMembers(self) -> bool: ...
    @IgnoreShouldSerializeMembers.setter
    def IgnoreShouldSerializeMembers(self, value: bool) -> bool: ...
    @property
    def NamingStrategy(self) -> NamingStrategy: ...
    @NamingStrategy.setter
    def NamingStrategy(self, value: NamingStrategy) -> NamingStrategy: ...
    @property
    def SerializeCompilerGeneratedMembers(self) -> bool: ...
    @SerializeCompilerGeneratedMembers.setter
    def SerializeCompilerGeneratedMembers(self, value: bool) -> bool: ...
    def ResolveContract(self, type: typing.Type[typing.Any]) -> JsonContract: ...


class DefaultContractResolver(IContractResolver):
    def __init__(self) -> None: ...
    @property
    def DefaultMembersSearchFlags(self) -> BindingFlags: ...
    @DefaultMembersSearchFlags.setter
    def DefaultMembersSearchFlags(self, value: BindingFlags) -> BindingFlags: ...
    @property
    def DynamicCodeGeneration(self) -> bool: ...
    @property
    def IgnoreIsSpecifiedMembers(self) -> bool: ...
    @IgnoreIsSpecifiedMembers.setter
    def IgnoreIsSpecifiedMembers(self, value: bool) -> bool: ...
    @property
    def IgnoreSerializableAttribute(self) -> bool: ...
    @IgnoreSerializableAttribute.setter
    def IgnoreSerializableAttribute(self, value: bool) -> bool: ...
    @property
    def IgnoreSerializableInterface(self) -> bool: ...
    @IgnoreSerializableInterface.setter
    def IgnoreSerializableInterface(self, value: bool) -> bool: ...
    @property
    def IgnoreShouldSerializeMembers(self) -> bool: ...
    @IgnoreShouldSerializeMembers.setter
    def IgnoreShouldSerializeMembers(self, value: bool) -> bool: ...
    @property
    def NamingStrategy(self) -> NamingStrategy: ...
    @NamingStrategy.setter
    def NamingStrategy(self, value: NamingStrategy) -> NamingStrategy: ...
    @property
    def SerializeCompilerGeneratedMembers(self) -> bool: ...
    @SerializeCompilerGeneratedMembers.setter
    def SerializeCompilerGeneratedMembers(self, value: bool) -> bool: ...
    def GetResolvedPropertyName(self, propertyName: str) -> str: ...
    def ResolveContract(self, type: typing.Type[typing.Any]) -> JsonContract: ...


class DefaultNamingStrategy(NamingStrategy):
    def __init__(self) -> None: ...
    @property
    def OverrideSpecifiedNames(self) -> bool: ...
    @OverrideSpecifiedNames.setter
    def OverrideSpecifiedNames(self, value: bool) -> bool: ...
    @property
    def ProcessDictionaryKeys(self) -> bool: ...
    @ProcessDictionaryKeys.setter
    def ProcessDictionaryKeys(self, value: bool) -> bool: ...
    @property
    def ProcessExtensionDataNames(self) -> bool: ...
    @ProcessExtensionDataNames.setter
    def ProcessExtensionDataNames(self, value: bool) -> bool: ...


class DefaultSerializationBinder(SerializationBinder, ISerializationBinder):
    def __init__(self) -> None: ...
    def BindToName(self, serializedType: typing.Type[typing.Any], assemblyName: clr.Reference[str], typeName: clr.Reference[str]) -> None: ...
    def BindToType(self, assemblyName: str, typeName: str) -> typing.Type[typing.Any]: ...


class DiagnosticsTraceWriter(ITraceWriter):
    def __init__(self) -> None: ...
    @property
    def LevelFilter(self) -> TraceLevel: ...
    @LevelFilter.setter
    def LevelFilter(self, value: TraceLevel) -> TraceLevel: ...
    def Trace(self, level: TraceLevel, message: str, ex: Exception) -> None: ...


class DynamicValueProvider(IValueProvider):
    def __init__(self, memberInfo: MemberInfo) -> None: ...
    def GetValue(self, target: typing.Any) -> typing.Any: ...
    def SetValue(self, target: typing.Any, value: typing.Any) -> None: ...


class ErrorContext:
    @property
    def Error(self) -> Exception: ...
    @property
    def Handled(self) -> bool: ...
    @Handled.setter
    def Handled(self, value: bool) -> bool: ...
    @property
    def Member(self) -> typing.Any: ...
    @property
    def OriginalObject(self) -> typing.Any: ...
    @property
    def Path(self) -> str: ...


class ErrorEventArgs(EventArgs):
    def __init__(self, currentObject: typing.Any, errorContext: ErrorContext) -> None: ...
    @property
    def CurrentObject(self) -> typing.Any: ...
    @property
    def ErrorContext(self) -> ErrorContext: ...


class ExpressionValueProvider(IValueProvider):
    def __init__(self, memberInfo: MemberInfo) -> None: ...
    def GetValue(self, target: typing.Any) -> typing.Any: ...
    def SetValue(self, target: typing.Any, value: typing.Any) -> None: ...


class ExtensionDataGetter(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, o: typing.Any, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> IEnumerable_1[KeyValuePair_2[typing.Any, typing.Any]]: ...
    def Invoke(self, o: typing.Any) -> IEnumerable_1[KeyValuePair_2[typing.Any, typing.Any]]: ...


class ExtensionDataSetter(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, o: typing.Any, key: str, value: typing.Any, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, o: typing.Any, key: str, value: typing.Any) -> None: ...


class IAttributeProvider(typing.Protocol):
    # Skipped GetAttributes due to it being static, abstract and generic.

    GetAttributes : GetAttributes_MethodGroup
    class GetAttributes_MethodGroup:
        @typing.overload
        def __call__(self, inherit: bool) -> IList_1[Attribute]:...
        @typing.overload
        def __call__(self, attributeType: typing.Type[typing.Any], inherit: bool) -> IList_1[Attribute]:...



class IContractResolver(typing.Protocol):
    @abc.abstractmethod
    def ResolveContract(self, type: typing.Type[typing.Any]) -> JsonContract: ...


class IReferenceResolver(typing.Protocol):
    @abc.abstractmethod
    def AddReference(self, context: typing.Any, reference: str, value: typing.Any) -> None: ...
    @abc.abstractmethod
    def GetReference(self, context: typing.Any, value: typing.Any) -> str: ...
    @abc.abstractmethod
    def IsReferenced(self, context: typing.Any, value: typing.Any) -> bool: ...
    @abc.abstractmethod
    def ResolveReference(self, context: typing.Any, reference: str) -> typing.Any: ...


class ISerializationBinder(typing.Protocol):
    @abc.abstractmethod
    def BindToName(self, serializedType: typing.Type[typing.Any], assemblyName: clr.Reference[str], typeName: clr.Reference[str]) -> None: ...
    @abc.abstractmethod
    def BindToType(self, assemblyName: str, typeName: str) -> typing.Type[typing.Any]: ...


class ITraceWriter(typing.Protocol):
    @property
    def LevelFilter(self) -> TraceLevel: ...
    @abc.abstractmethod
    def Trace(self, level: TraceLevel, message: str, ex: Exception) -> None: ...


class IValueProvider(typing.Protocol):
    @abc.abstractmethod
    def GetValue(self, target: typing.Any) -> typing.Any: ...
    @abc.abstractmethod
    def SetValue(self, target: typing.Any, value: typing.Any) -> None: ...


class JsonArrayContract(JsonContainerContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def CollectionItemType(self) -> typing.Type[typing.Any]: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def HasParameterizedCreator(self) -> bool: ...
    @HasParameterizedCreator.setter
    def HasParameterizedCreator(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsMultidimensionalArray(self) -> bool: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OverrideCreator(self) -> ObjectConstructor_1[typing.Any]: ...
    @OverrideCreator.setter
    def OverrideCreator(self, value: ObjectConstructor_1[typing.Any]) -> ObjectConstructor_1[typing.Any]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonContainerContract(JsonContract):
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonContract(abc.ABC):
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonDictionaryContract(JsonContainerContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def DictionaryKeyResolver(self) -> Func_2[str, str]: ...
    @DictionaryKeyResolver.setter
    def DictionaryKeyResolver(self, value: Func_2[str, str]) -> Func_2[str, str]: ...
    @property
    def DictionaryKeyType(self) -> typing.Type[typing.Any]: ...
    @property
    def DictionaryValueType(self) -> typing.Type[typing.Any]: ...
    @property
    def HasParameterizedCreator(self) -> bool: ...
    @HasParameterizedCreator.setter
    def HasParameterizedCreator(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OverrideCreator(self) -> ObjectConstructor_1[typing.Any]: ...
    @OverrideCreator.setter
    def OverrideCreator(self, value: ObjectConstructor_1[typing.Any]) -> ObjectConstructor_1[typing.Any]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonDynamicContract(JsonContainerContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def Properties(self) -> JsonPropertyCollection: ...
    @property
    def PropertyNameResolver(self) -> Func_2[str, str]: ...
    @PropertyNameResolver.setter
    def PropertyNameResolver(self, value: Func_2[str, str]) -> Func_2[str, str]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonISerializableContract(JsonContainerContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ISerializableCreator(self) -> ObjectConstructor_1[typing.Any]: ...
    @ISerializableCreator.setter
    def ISerializableCreator(self, value: ObjectConstructor_1[typing.Any]) -> ObjectConstructor_1[typing.Any]: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonLinqContract(JsonContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonObjectContract(JsonContainerContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def CreatorParameters(self) -> JsonPropertyCollection: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def ExtensionDataGetter(self) -> ExtensionDataGetter: ...
    @ExtensionDataGetter.setter
    def ExtensionDataGetter(self, value: ExtensionDataGetter) -> ExtensionDataGetter: ...
    @property
    def ExtensionDataNameResolver(self) -> Func_2[str, str]: ...
    @ExtensionDataNameResolver.setter
    def ExtensionDataNameResolver(self, value: Func_2[str, str]) -> Func_2[str, str]: ...
    @property
    def ExtensionDataSetter(self) -> ExtensionDataSetter: ...
    @ExtensionDataSetter.setter
    def ExtensionDataSetter(self, value: ExtensionDataSetter) -> ExtensionDataSetter: ...
    @property
    def ExtensionDataValueType(self) -> typing.Type[typing.Any]: ...
    @ExtensionDataValueType.setter
    def ExtensionDataValueType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemNullValueHandling(self) -> typing.Optional[NullValueHandling]: ...
    @ItemNullValueHandling.setter
    def ItemNullValueHandling(self, value: typing.Optional[NullValueHandling]) -> typing.Optional[NullValueHandling]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemRequired(self) -> typing.Optional[Required]: ...
    @ItemRequired.setter
    def ItemRequired(self, value: typing.Optional[Required]) -> typing.Optional[Required]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def MemberSerialization(self) -> MemberSerialization: ...
    @MemberSerialization.setter
    def MemberSerialization(self, value: MemberSerialization) -> MemberSerialization: ...
    @property
    def MissingMemberHandling(self) -> typing.Optional[MissingMemberHandling]: ...
    @MissingMemberHandling.setter
    def MissingMemberHandling(self, value: typing.Optional[MissingMemberHandling]) -> typing.Optional[MissingMemberHandling]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OverrideCreator(self) -> ObjectConstructor_1[typing.Any]: ...
    @OverrideCreator.setter
    def OverrideCreator(self, value: ObjectConstructor_1[typing.Any]) -> ObjectConstructor_1[typing.Any]: ...
    @property
    def Properties(self) -> JsonPropertyCollection: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonPrimitiveContract(JsonContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class JsonProperty:
    def __init__(self) -> None: ...
    @property
    def AttributeProvider(self) -> IAttributeProvider: ...
    @AttributeProvider.setter
    def AttributeProvider(self, value: IAttributeProvider) -> IAttributeProvider: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def DeclaringType(self) -> typing.Type[typing.Any]: ...
    @DeclaringType.setter
    def DeclaringType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultValue(self) -> typing.Any: ...
    @DefaultValue.setter
    def DefaultValue(self, value: typing.Any) -> typing.Any: ...
    @property
    def DefaultValueHandling(self) -> typing.Optional[DefaultValueHandling]: ...
    @DefaultValueHandling.setter
    def DefaultValueHandling(self, value: typing.Optional[DefaultValueHandling]) -> typing.Optional[DefaultValueHandling]: ...
    @property
    def GetIsSpecified(self) -> Predicate_1[typing.Any]: ...
    @GetIsSpecified.setter
    def GetIsSpecified(self, value: Predicate_1[typing.Any]) -> Predicate_1[typing.Any]: ...
    @property
    def HasMemberAttribute(self) -> bool: ...
    @HasMemberAttribute.setter
    def HasMemberAttribute(self, value: bool) -> bool: ...
    @property
    def Ignored(self) -> bool: ...
    @Ignored.setter
    def Ignored(self, value: bool) -> bool: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def IsRequiredSpecified(self) -> bool: ...
    @property
    def ItemConverter(self) -> JsonConverter: ...
    @ItemConverter.setter
    def ItemConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def ItemIsReference(self) -> typing.Optional[bool]: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def ItemReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def ItemTypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def MemberConverter(self) -> JsonConverter: ...
    @MemberConverter.setter
    def MemberConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def NullValueHandling(self) -> typing.Optional[NullValueHandling]: ...
    @NullValueHandling.setter
    def NullValueHandling(self, value: typing.Optional[NullValueHandling]) -> typing.Optional[NullValueHandling]: ...
    @property
    def ObjectCreationHandling(self) -> typing.Optional[ObjectCreationHandling]: ...
    @ObjectCreationHandling.setter
    def ObjectCreationHandling(self, value: typing.Optional[ObjectCreationHandling]) -> typing.Optional[ObjectCreationHandling]: ...
    @property
    def Order(self) -> typing.Optional[int]: ...
    @Order.setter
    def Order(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def PropertyName(self) -> str: ...
    @PropertyName.setter
    def PropertyName(self, value: str) -> str: ...
    @property
    def PropertyType(self) -> typing.Type[typing.Any]: ...
    @PropertyType.setter
    def PropertyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def Readable(self) -> bool: ...
    @Readable.setter
    def Readable(self, value: bool) -> bool: ...
    @property
    def ReferenceLoopHandling(self) -> typing.Optional[ReferenceLoopHandling]: ...
    @ReferenceLoopHandling.setter
    def ReferenceLoopHandling(self, value: typing.Optional[ReferenceLoopHandling]) -> typing.Optional[ReferenceLoopHandling]: ...
    @property
    def Required(self) -> Required: ...
    @Required.setter
    def Required(self, value: Required) -> Required: ...
    @property
    def SetIsSpecified(self) -> Action_2[typing.Any, typing.Any]: ...
    @SetIsSpecified.setter
    def SetIsSpecified(self, value: Action_2[typing.Any, typing.Any]) -> Action_2[typing.Any, typing.Any]: ...
    @property
    def ShouldDeserialize(self) -> Predicate_1[typing.Any]: ...
    @ShouldDeserialize.setter
    def ShouldDeserialize(self, value: Predicate_1[typing.Any]) -> Predicate_1[typing.Any]: ...
    @property
    def ShouldSerialize(self) -> Predicate_1[typing.Any]: ...
    @ShouldSerialize.setter
    def ShouldSerialize(self, value: Predicate_1[typing.Any]) -> Predicate_1[typing.Any]: ...
    @property
    def TypeNameHandling(self) -> typing.Optional[TypeNameHandling]: ...
    @TypeNameHandling.setter
    def TypeNameHandling(self, value: typing.Optional[TypeNameHandling]) -> typing.Optional[TypeNameHandling]: ...
    @property
    def UnderlyingName(self) -> str: ...
    @UnderlyingName.setter
    def UnderlyingName(self, value: str) -> str: ...
    @property
    def ValueProvider(self) -> IValueProvider: ...
    @ValueProvider.setter
    def ValueProvider(self, value: IValueProvider) -> IValueProvider: ...
    @property
    def Writable(self) -> bool: ...
    @Writable.setter
    def Writable(self, value: bool) -> bool: ...
    def ToString(self) -> str: ...


class JsonPropertyCollection(KeyedCollection_2[str, JsonProperty]):
    def __init__(self, type: typing.Type[typing.Any]) -> None: ...
    @property
    def Comparer(self) -> IEqualityComparer_1[str]: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> JsonProperty: ...
    @property
    def Item(self) -> JsonProperty: ...
    @Item.setter
    def Item(self, value: JsonProperty) -> JsonProperty: ...
    def AddProperty(self, property: JsonProperty) -> None: ...
    def GetClosestMatchProperty(self, propertyName: str) -> JsonProperty: ...
    def GetProperty(self, propertyName: str, comparisonType: StringComparison) -> JsonProperty: ...


class JsonStringContract(JsonPrimitiveContract):
    def __init__(self, underlyingType: typing.Type[typing.Any]) -> None: ...
    @property
    def Converter(self) -> JsonConverter: ...
    @Converter.setter
    def Converter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def CreatedType(self) -> typing.Type[typing.Any]: ...
    @CreatedType.setter
    def CreatedType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def DefaultCreator(self) -> Func_1[typing.Any]: ...
    @DefaultCreator.setter
    def DefaultCreator(self, value: Func_1[typing.Any]) -> Func_1[typing.Any]: ...
    @property
    def DefaultCreatorNonPublic(self) -> bool: ...
    @DefaultCreatorNonPublic.setter
    def DefaultCreatorNonPublic(self, value: bool) -> bool: ...
    @property
    def InternalConverter(self) -> JsonConverter: ...
    @InternalConverter.setter
    def InternalConverter(self, value: JsonConverter) -> JsonConverter: ...
    @property
    def IsReference(self) -> typing.Optional[bool]: ...
    @IsReference.setter
    def IsReference(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def OnDeserializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnDeserializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnErrorCallbacks(self) -> IList_1[SerializationErrorCallback]: ...
    @property
    def OnSerializedCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def OnSerializingCallbacks(self) -> IList_1[SerializationCallback]: ...
    @property
    def UnderlyingType(self) -> typing.Type[typing.Any]: ...


class KebabCaseNamingStrategy(NamingStrategy):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool, processExtensionDataNames: bool) -> None: ...
    @property
    def OverrideSpecifiedNames(self) -> bool: ...
    @OverrideSpecifiedNames.setter
    def OverrideSpecifiedNames(self, value: bool) -> bool: ...
    @property
    def ProcessDictionaryKeys(self) -> bool: ...
    @ProcessDictionaryKeys.setter
    def ProcessDictionaryKeys(self, value: bool) -> bool: ...
    @property
    def ProcessExtensionDataNames(self) -> bool: ...
    @ProcessExtensionDataNames.setter
    def ProcessExtensionDataNames(self, value: bool) -> bool: ...


class MemoryTraceWriter(ITraceWriter):
    def __init__(self) -> None: ...
    @property
    def LevelFilter(self) -> TraceLevel: ...
    @LevelFilter.setter
    def LevelFilter(self, value: TraceLevel) -> TraceLevel: ...
    def GetTraceMessages(self) -> IEnumerable_1[str]: ...
    def ToString(self) -> str: ...
    def Trace(self, level: TraceLevel, message: str, ex: Exception) -> None: ...


class NamingStrategy(abc.ABC):
    @property
    def OverrideSpecifiedNames(self) -> bool: ...
    @OverrideSpecifiedNames.setter
    def OverrideSpecifiedNames(self, value: bool) -> bool: ...
    @property
    def ProcessDictionaryKeys(self) -> bool: ...
    @ProcessDictionaryKeys.setter
    def ProcessDictionaryKeys(self, value: bool) -> bool: ...
    @property
    def ProcessExtensionDataNames(self) -> bool: ...
    @ProcessExtensionDataNames.setter
    def ProcessExtensionDataNames(self, value: bool) -> bool: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetDictionaryKey(self, key: str) -> str: ...
    def GetExtensionDataName(self, name: str) -> str: ...
    def GetHashCode(self) -> int: ...
    def GetPropertyName(self, name: str, hasSpecifiedName: bool) -> str: ...


class ObjectConstructor_GenericClasses(abc.ABCMeta):
    Generic_ObjectConstructor_GenericClasses_ObjectConstructor_1_T = typing.TypeVar('Generic_ObjectConstructor_GenericClasses_ObjectConstructor_1_T')
    def __getitem__(self, types : typing.Type[Generic_ObjectConstructor_GenericClasses_ObjectConstructor_1_T]) -> typing.Type[ObjectConstructor_1[Generic_ObjectConstructor_GenericClasses_ObjectConstructor_1_T]]: ...

ObjectConstructor : ObjectConstructor_GenericClasses

ObjectConstructor_1_T = typing.TypeVar('ObjectConstructor_1_T')
class ObjectConstructor_1(typing.Generic[ObjectConstructor_1_T], MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, args: Array_1[typing.Any], callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> typing.Any: ...
    def Invoke(self, args: Array_1[typing.Any]) -> typing.Any: ...


class OnErrorAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class ReflectionAttributeProvider(IAttributeProvider):
    def __init__(self, attributeProvider: typing.Any) -> None: ...
    # Skipped GetAttributes due to it being static, abstract and generic.

    GetAttributes : GetAttributes_MethodGroup
    class GetAttributes_MethodGroup:
        @typing.overload
        def __call__(self, inherit: bool) -> IList_1[Attribute]:...
        @typing.overload
        def __call__(self, attributeType: typing.Type[typing.Any], inherit: bool) -> IList_1[Attribute]:...



class ReflectionValueProvider(IValueProvider):
    def __init__(self, memberInfo: MemberInfo) -> None: ...
    def GetValue(self, target: typing.Any) -> typing.Any: ...
    def SetValue(self, target: typing.Any, value: typing.Any) -> None: ...


class SerializationCallback(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, o: typing.Any, context: StreamingContext, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, o: typing.Any, context: StreamingContext) -> None: ...


class SerializationErrorCallback(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, o: typing.Any, context: StreamingContext, errorContext: ErrorContext, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, o: typing.Any, context: StreamingContext, errorContext: ErrorContext) -> None: ...


class SnakeCaseNamingStrategy(NamingStrategy):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool) -> None: ...
    @typing.overload
    def __init__(self, processDictionaryKeys: bool, overrideSpecifiedNames: bool, processExtensionDataNames: bool) -> None: ...
    @property
    def OverrideSpecifiedNames(self) -> bool: ...
    @OverrideSpecifiedNames.setter
    def OverrideSpecifiedNames(self, value: bool) -> bool: ...
    @property
    def ProcessDictionaryKeys(self) -> bool: ...
    @ProcessDictionaryKeys.setter
    def ProcessDictionaryKeys(self, value: bool) -> bool: ...
    @property
    def ProcessExtensionDataNames(self) -> bool: ...
    @ProcessExtensionDataNames.setter
    def ProcessExtensionDataNames(self, value: bool) -> bool: ...

