import typing, abc
from System.Threading.Tasks import Task_1
from System.IO.Pipes import NamedPipeClientStream
from System.Threading import CancellationToken
from System import TimeSpan, MulticastDelegate, IAsyncResult, AsyncCallback
from System.Reflection import MethodInfo

class IIpcClientPipeConnector(typing.Protocol):
    @abc.abstractmethod
    def ConnectNamedPipeAsync(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext) -> Task_1[IpcClientNamedPipeConnectResult]: ...


class IpcClientNamedPipeConnectResult:
    def __init__(self, success: bool, reason: str = ...) -> None: ...
    @property
    def Reason(self) -> str: ...
    @property
    def Success(self) -> bool: ...


class IpcClientPipeConnectionContext:
    def __init__(self, peerName: str, namedPipeClientStream: NamedPipeClientStream, cancellationToken: CancellationToken, isReConnect: bool) -> None: ...
    @property
    def CancellationToken(self) -> CancellationToken: ...
    @property
    def IsReConnect(self) -> bool: ...
    @property
    def NamedPipeClientStream(self) -> NamedPipeClientStream: ...
    @property
    def PeerName(self) -> str: ...


class IpcClientPipeConnector(IIpcClientPipeConnector):
    def __init__(self, canContinue: IpcClientPipeConnector.CanContinueDelegate, stepTimeout: typing.Optional[TimeSpan] = ..., stepSleepTimeGetter: IpcClientPipeConnector.GetStepSleepTimeDelegate = ...) -> None: ...
    @property
    def CanContinue(self) -> IpcClientPipeConnector.CanContinueDelegate: ...
    @classmethod
    @property
    def DefaultStepSleepTime(cls) -> TimeSpan: ...
    @classmethod
    @property
    def DefaultStepTimeout(cls) -> TimeSpan: ...
    @property
    def StepSleepTimeGetter(self) -> IpcClientPipeConnector.GetStepSleepTimeDelegate: ...
    @property
    def StepTimeout(self) -> TimeSpan: ...
    def ConnectNamedPipeAsync(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext) -> Task_1[IpcClientNamedPipeConnectResult]: ...
    @staticmethod
    def DefaultGetStepSleepTime(ipcClientPipeConnectionContext: IpcClientPipeConnectionContext, stepCount: int) -> TimeSpan: ...

    class CanContinueDelegate(MulticastDelegate):
        def __init__(self, object: typing.Any, method: int) -> None: ...
        @property
        def Method(self) -> MethodInfo: ...
        @property
        def Target(self) -> typing.Any: ...
        def BeginInvoke(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
        def EndInvoke(self, result: IAsyncResult) -> bool: ...
        def Invoke(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext) -> bool: ...


    class GetStepSleepTimeDelegate(MulticastDelegate):
        def __init__(self, object: typing.Any, method: int) -> None: ...
        @property
        def Method(self) -> MethodInfo: ...
        @property
        def Target(self) -> typing.Any: ...
        def BeginInvoke(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext, stepCount: int, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
        def EndInvoke(self, result: IAsyncResult) -> TimeSpan: ...
        def Invoke(self, ipcClientPipeConnectionContext: IpcClientPipeConnectionContext, stepCount: int) -> TimeSpan: ...


