import typing, abc
from dotnetCampus.Ipc.Messages import Ack, IpcMessageBody
from System.Collections.Generic import IEnumerable_1

class IIpcMessageInspector(typing.Protocol):
    @abc.abstractmethod
    def Receive(self, context: IpcMessageInspectionContext) -> None: ...
    @abc.abstractmethod
    def ReceiveCore(self, context: IpcMessageInspectionContext) -> None: ...
    @abc.abstractmethod
    def Send(self, context: IpcMessageInspectionContext) -> None: ...
    @abc.abstractmethod
    def SendCore(self, context: IpcMessageInspectionContext) -> None: ...


class IpcMessageInspectionContext:
    @property
    def Ack(self) -> typing.Optional[Ack]: ...
    @property
    def LocalPeerName(self) -> str: ...
    @property
    def RemotePeerName(self) -> str: ...
    @property
    def Tag(self) -> str: ...
    def GetMessageParts(self) -> IEnumerable_1[IpcMessageBody]: ...


class IpcMessageInspectorManager:
    @staticmethod
    def FromLocalPeerName(peerName: str) -> IpcMessageInspectorManager: ...
    def RegisterInspector(self, inspector: IIpcMessageInspector) -> None: ...

