import typing, abc
from System import Array_1
from System.Buffers import ArrayPool_1

class ISharedArrayPool(typing.Protocol):
    @abc.abstractmethod
    def Rent(self, minLength: int) -> Array_1[int]: ...
    @abc.abstractmethod
    def Return(self, array: Array_1[int]) -> None: ...


class SharedArrayPool(ISharedArrayPool):
    def __init__(self, arrayPool: ArrayPool_1[int] = ...) -> None: ...
    @property
    def ArrayPool(self) -> ArrayPool_1[int]: ...
    def Rent(self, minLength: int) -> Array_1[int]: ...
    def Return(self, array: Array_1[int]) -> None: ...

