import typing, clr, abc
from System import EventArgs, Func_2, Array_1, Exception
from dotnetCampus.Ipc.Messages import Ack, IIpcResponseMessage, IpcMessage, IpcMessageBody, IpcClientRequestMessageId
from dotnetCampus.Ipc import IIpcRequestHandler, IPeerProxy
from System.Threading.Tasks import Task_1
from dotnetCampus.Ipc.Threading import CustomIpcThreadPoolBase, IpcTaskScheduling
from dotnetCampus.Ipc.Pipes.PipeConnectors import IIpcClientPipeConnector
from dotnetCampus.Ipc.Utils.Logging import IpcLogger
from dotnetCampus.Ipc.Utils.Buffers import ISharedArrayPool
from dotnetCampus.Ipc.Pipes import IpcProvider, PeerProxy
from System.Collections.Generic import List_1

class AckArgs(EventArgs):
    def __init__(self, peerName: str, ack: clr.Reference[Ack]) -> None: ...
    @property
    def Ack(self) -> Ack: ...
    @property
    def PeerName(self) -> str: ...


class BrokenReason(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Unknown : BrokenReason # 0
    BusinessExit : BrokenReason # 1


class DelegateIpcRequestHandler(IIpcRequestHandler):
    @typing.overload
    def __init__(self, handler: Func_2[IIpcRequestContext, Task_1[IIpcResponseMessage]]) -> None: ...
    @typing.overload
    def __init__(self, handler: Func_2[IIpcRequestContext, IIpcResponseMessage]) -> None: ...


class IIpcRequestContext(typing.Protocol):
    @property
    def Handled(self) -> bool: ...
    @Handled.setter
    def Handled(self, value: bool) -> bool: ...
    @property
    def IpcBufferMessage(self) -> IpcMessage: ...
    @property
    def Peer(self) -> IPeerProxy: ...


class IpcClientRequestArgs(EventArgs):
    @property
    def IpcMessageBody(self) -> IpcMessageBody: ...
    @property
    def MessageId(self) -> IpcClientRequestMessageId: ...


class IpcConfiguration:
    def __init__(self) -> None: ...
    MaxMessageLength : int
    @property
    def AutoReconnectPeers(self) -> bool: ...
    @AutoReconnectPeers.setter
    def AutoReconnectPeers(self, value: bool) -> bool: ...
    @property
    def CustomIpcThreadPool(self) -> CustomIpcThreadPoolBase: ...
    @CustomIpcThreadPool.setter
    def CustomIpcThreadPool(self, value: CustomIpcThreadPoolBase) -> CustomIpcThreadPoolBase: ...
    @property
    def DefaultIpcRequestHandler(self) -> IIpcRequestHandler: ...
    @DefaultIpcRequestHandler.setter
    def DefaultIpcRequestHandler(self, value: IIpcRequestHandler) -> IIpcRequestHandler: ...
    @property
    def IpcClientPipeConnector(self) -> IIpcClientPipeConnector: ...
    @IpcClientPipeConnector.setter
    def IpcClientPipeConnector(self, value: IIpcClientPipeConnector) -> IIpcClientPipeConnector: ...
    @property
    def IpcLoggerProvider(self) -> Func_2[str, IpcLogger]: ...
    @IpcLoggerProvider.setter
    def IpcLoggerProvider(self, value: Func_2[str, IpcLogger]) -> Func_2[str, IpcLogger]: ...
    @property
    def IpcTaskScheduling(self) -> IpcTaskScheduling: ...
    @IpcTaskScheduling.setter
    def IpcTaskScheduling(self, value: IpcTaskScheduling) -> IpcTaskScheduling: ...
    @property
    def MessageHeader(self) -> Array_1[int]: ...
    @MessageHeader.setter
    def MessageHeader(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def SharedArrayPool(self) -> ISharedArrayPool: ...
    @SharedArrayPool.setter
    def SharedArrayPool(self, value: ISharedArrayPool) -> ISharedArrayPool: ...


class IpcContext:
    def __init__(self, ipcProvider: IpcProvider, pipeName: str, ipcConfiguration: IpcConfiguration = ...) -> None: ...
    DefaultPipeName : str
    @property
    def PipeName(self) -> str: ...
    def ToString(self) -> str: ...


class IpcRequest:
    def __init__(self) -> None: ...
    @property
    def GenericArgumentList(self) -> List_1[IpcSerializableType]: ...
    @GenericArgumentList.setter
    def GenericArgumentList(self, value: List_1[IpcSerializableType]) -> List_1[IpcSerializableType]: ...
    @property
    def MethodName(self) -> str: ...
    @MethodName.setter
    def MethodName(self, value: str) -> str: ...
    @property
    def ObjectId(self) -> int: ...
    @ObjectId.setter
    def ObjectId(self, value: int) -> int: ...
    @property
    def ObjectType(self) -> IpcSerializableType: ...
    @ObjectType.setter
    def ObjectType(self, value: IpcSerializableType) -> IpcSerializableType: ...
    @property
    def ParameterList(self) -> List_1[IpcRequestParameter]: ...
    @ParameterList.setter
    def ParameterList(self, value: List_1[IpcRequestParameter]) -> List_1[IpcRequestParameter]: ...
    @property
    def ReturnType(self) -> IpcSerializableType: ...
    @ReturnType.setter
    def ReturnType(self, value: IpcSerializableType) -> IpcSerializableType: ...


class IpcRequestParameter:
    def __init__(self) -> None: ...
    @property
    def ParameterType(self) -> IpcSerializableType: ...
    @ParameterType.setter
    def ParameterType(self, value: IpcSerializableType) -> IpcSerializableType: ...
    @property
    def Value(self) -> typing.Any: ...
    @Value.setter
    def Value(self, value: typing.Any) -> typing.Any: ...


class IpcRequestParameterType(IpcSerializableType):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, type: typing.Type[typing.Any]) -> None: ...
    @property
    def TypeFullName(self) -> str: ...
    @TypeFullName.setter
    def TypeFullName(self, value: str) -> str: ...


class IpcResponse:
    def __init__(self, status: IpcStatus, data: typing.Any, errorMessage: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> typing.Any: ...
    @property
    def ErrorMessage(self) -> str: ...
    @ErrorMessage.setter
    def ErrorMessage(self, value: str) -> str: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Status(self) -> IpcStatus: ...
    def Succeed(self) -> bool: ...
    @staticmethod
    def Success(data: typing.Any) -> IpcResponse: ...
    # Skipped BadRequest due to it being static, abstract and generic.

    BadRequest : BadRequest_MethodGroup
    class BadRequest_MethodGroup:
        @typing.overload
        def __call__(self) -> IpcResponse:...
        @typing.overload
        def __call__(self, errorDetails: str) -> IpcResponse:...
        @typing.overload
        def __call__(self, errorDetails: str, innerException: Exception) -> IpcResponse:...

    # Skipped InternalServerError due to it being static, abstract and generic.

    InternalServerError : InternalServerError_MethodGroup
    class InternalServerError_MethodGroup:
        @typing.overload
        def __call__(self) -> IpcResponse:...
        @typing.overload
        def __call__(self, errorDetails: str) -> IpcResponse:...
        @typing.overload
        def __call__(self, errorDetails: str, innerException: Exception) -> IpcResponse:...



class IpcSerializableType:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, type: typing.Type[typing.Any]) -> None: ...
    @property
    def TypeFullName(self) -> str: ...
    @TypeFullName.setter
    def TypeFullName(self, value: str) -> str: ...


class IpcStatus(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Unknown : IpcStatus # 0
    Ok : IpcStatus # 200
    BadRequest : IpcStatus # 400
    InternalServerError : IpcStatus # 500


class IPeerConnectionBrokenArgs(typing.Protocol):
    pass


class IPeerMessageArgs(typing.Protocol):
    @property
    def Message(self) -> IpcMessage: ...
    @property
    def PeerName(self) -> str: ...
    @abc.abstractmethod
    def TryGetPayload(self, requiredHeader: Array_1[int], subMessage: clr.Reference[IpcMessage]) -> bool: ...


class IPeerReconnectedArgs(typing.Protocol):
    pass


class KnownMessageHeaders(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    RemoteObjectMessageHeader : KnownMessageHeaders # 1382895466
    JsonIpcDirectRoutedMessageHeader : KnownMessageHeaders # 8381887494726054730
    RawByteIpcDirectRoutedMessageHeader : KnownMessageHeaders # 8381887494823769938


class PeerConnectedArgs(EventArgs):
    def __init__(self, peer: PeerProxy) -> None: ...
    @property
    def Peer(self) -> PeerProxy: ...


class PeerConnectionBrokenArgs(EventArgs, IPeerConnectionBrokenArgs):
    def __init__(self) -> None: ...


class PeerMessageArgs(EventArgs, IPeerMessageArgs):
    @property
    def Ack(self) -> Ack: ...
    @property
    def Handle(self) -> bool: ...
    @Handle.setter
    def Handle(self, value: bool) -> bool: ...
    @property
    def HandlerMessage(self) -> str: ...
    @HandlerMessage.setter
    def HandlerMessage(self, value: str) -> str: ...
    @property
    def Message(self) -> IpcMessage: ...
    @property
    def PeerName(self) -> str: ...
    def SetHandle(self, message: str) -> None: ...
    def TryGetPayload(self, requiredHeader: Array_1[int], subMessage: clr.Reference[IpcMessage]) -> bool: ...

