import typing
from System.Collections.Generic import IEnumerable_1

class ValidationResult:
    @typing.overload
    def __init__(self, errorMessage: str) -> None: ...
    @typing.overload
    def __init__(self, errorMessage: str, memberNames: IEnumerable_1[str]) -> None: ...
    Success : ValidationResult
    @property
    def ErrorMessage(self) -> str: ...
    @ErrorMessage.setter
    def ErrorMessage(self, value: str) -> str: ...
    @property
    def MemberNames(self) -> IEnumerable_1[str]: ...
    def ToString(self) -> str: ...

