import typing, abc
from ClassIsland.Shared.Models.Profile import ClassPlan, Subject, TimeLayoutItem, Profile
from ClassIsland.Shared.Enums import TimeState
from System import TimeSpan, DateTime, Guid, Uri

class IFooService(typing.Protocol):
    @abc.abstractmethod
    def DoSomething(self) -> None: ...


class IPublicLessonsService(typing.Protocol):
    @property
    def CurrentClassPlan(self) -> ClassPlan: ...
    @CurrentClassPlan.setter
    def CurrentClassPlan(self, value: ClassPlan) -> ClassPlan: ...
    @property
    def CurrentSelectedIndex(self) -> int: ...
    @CurrentSelectedIndex.setter
    def CurrentSelectedIndex(self, value: int) -> int: ...
    @property
    def CurrentState(self) -> TimeState: ...
    @CurrentState.setter
    def CurrentState(self, value: TimeState) -> TimeState: ...
    @property
    def CurrentSubject(self) -> Subject: ...
    @CurrentSubject.setter
    def CurrentSubject(self, value: Subject) -> Subject: ...
    @property
    def CurrentTimeLayoutItem(self) -> TimeLayoutItem: ...
    @CurrentTimeLayoutItem.setter
    def CurrentTimeLayoutItem(self, value: TimeLayoutItem) -> TimeLayoutItem: ...
    @property
    def IsClassPlanEnabled(self) -> bool: ...
    @IsClassPlanEnabled.setter
    def IsClassPlanEnabled(self, value: bool) -> bool: ...
    @property
    def IsClassPlanLoaded(self) -> bool: ...
    @IsClassPlanLoaded.setter
    def IsClassPlanLoaded(self, value: bool) -> bool: ...
    @property
    def IsLessonConfirmed(self) -> bool: ...
    @IsLessonConfirmed.setter
    def IsLessonConfirmed(self, value: bool) -> bool: ...
    @property
    def IsTimerRunning(self) -> bool: ...
    @property
    def NextBreakingTimeLayoutItem(self) -> TimeLayoutItem: ...
    @NextBreakingTimeLayoutItem.setter
    def NextBreakingTimeLayoutItem(self, value: TimeLayoutItem) -> TimeLayoutItem: ...
    @property
    def NextClassSubject(self) -> Subject: ...
    @NextClassSubject.setter
    def NextClassSubject(self, value: Subject) -> Subject: ...
    @property
    def NextClassTimeLayoutItem(self) -> TimeLayoutItem: ...
    @NextClassTimeLayoutItem.setter
    def NextClassTimeLayoutItem(self, value: TimeLayoutItem) -> TimeLayoutItem: ...
    @property
    def OnBreakingTimeLeftTime(self) -> TimeSpan: ...
    @OnBreakingTimeLeftTime.setter
    def OnBreakingTimeLeftTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def OnClassLeftTime(self) -> TimeSpan: ...
    @OnClassLeftTime.setter
    def OnClassLeftTime(self, value: TimeSpan) -> TimeSpan: ...
    @abc.abstractmethod
    def GetClassPlanByDate(self, date: DateTime) -> ClassPlan: ...


class IPublicProfileService(typing.Protocol):
    @property
    def CurrentProfilePath(self) -> str: ...
    @CurrentProfilePath.setter
    def CurrentProfilePath(self, value: str) -> str: ...
    @property
    def IsCurrentProfileTrusted(self) -> bool: ...
    @property
    def Profile(self) -> Profile: ...
    @Profile.setter
    def Profile(self, value: Profile) -> Profile: ...
    @abc.abstractmethod
    def ClearTempClassPlan(self) -> None: ...
    @abc.abstractmethod
    def ClearTempClassPlanGroup(self) -> None: ...
    @abc.abstractmethod
    def CreateTempClassPlan(self, id: Guid, timeLayoutId: typing.Optional[Guid] = ..., enableDateTime: typing.Optional[DateTime] = ...) -> typing.Optional[Guid]: ...
    @abc.abstractmethod
    def SetupTempClassPlanGroup(self, key: Guid, expireTime: typing.Optional[DateTime] = ...) -> None: ...
    # Skipped ConvertToStdClassPlan due to it being static, abstract and generic.

    ConvertToStdClassPlan : ConvertToStdClassPlan_MethodGroup
    class ConvertToStdClassPlan_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, id: Guid) -> None:...

    # Skipped SaveProfile due to it being static, abstract and generic.

    SaveProfile : SaveProfile_MethodGroup
    class SaveProfile_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, filename: str) -> None:...



class IPublicUriNavigationService(typing.Protocol):
    @abc.abstractmethod
    def Navigate(self, uri: Uri) -> None: ...
    @abc.abstractmethod
    def NavigateWrapped(self, uri: Uri) -> None: ...

