import typing
from CommunityToolkit.Mvvm.ComponentModel import ObservableObject

class NotifyResult(ObservableObject):
    def __init__(self) -> None: ...
    @property
    def Overlay(self) -> str: ...
    @Overlay.setter
    def Overlay(self, value: str) -> str: ...
    @property
    def OverlayDuration(self) -> int: ...
    @OverlayDuration.setter
    def OverlayDuration(self, value: int) -> int: ...
    @property
    def OverlayType(self) -> OverlayType: ...
    @OverlayType.setter
    def OverlayType(self, value: OverlayType) -> OverlayType: ...
    @property
    def PickType(self) -> PickType: ...
    @PickType.setter
    def PickType(self, value: PickType) -> PickType: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def TitleDuration(self) -> int: ...
    @TitleDuration.setter
    def TitleDuration(self, value: int) -> int: ...


class OverlayType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Simple : OverlayType # 0
    Rolling : OverlayType # 1


class PickType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Person : PickType # 0
    Group : PickType # 1

