import typing, abc
from System import Array_1, Attribute, Func_1, Decimal, DateTime, DateTimeOffset, Enum, Guid, TimeSpan, Uri, Exception, IDisposable, IAsyncDisposable, EventHandler_1
from System.Xml import XmlDocument, XmlNode
from System.Xml.Linq import XDocument, XObject
from System.Collections.ObjectModel import Collection_1
from System.Runtime.Serialization import SerializationInfo, StreamingContext, SerializationBinder
from System.Collections import IDictionary, IEqualityComparer
from System.Reflection import MethodBase
from System.Globalization import CultureInfo
from System.Threading.Tasks import Task_1, Task
from System.Threading import CancellationToken
from Newtonsoft.Json.Serialization import IContractResolver, IReferenceResolver, ISerializationBinder, ITraceWriter, ErrorEventArgs
from System.Runtime.Serialization.Formatters import FormatterAssemblyStyle
from System.IO import TextReader, TextWriter
from System.Collections.Generic import IList_1
from Newtonsoft.Json.Schema import JsonSchema

class ConstructorHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : ConstructorHandling # 0
    AllowNonPublicDefaultConstructor : ConstructorHandling # 1


class DateFormatHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    IsoDateFormat : DateFormatHandling # 0
    MicrosoftDateFormat : DateFormatHandling # 1


class DateParseHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : DateParseHandling # 0
    DateTime : DateParseHandling # 1
    DateTimeOffset : DateParseHandling # 2


class DateTimeZoneHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Local : DateTimeZoneHandling # 0
    Utc : DateTimeZoneHandling # 1
    Unspecified : DateTimeZoneHandling # 2
    RoundtripKind : DateTimeZoneHandling # 3


class DefaultJsonNameTable(JsonNameTable):
    def __init__(self) -> None: ...
    def Add(self, key: str) -> str: ...
    def Get(self, key: Array_1[str], start: int, length: int) -> str: ...


class DefaultValueHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Include : DefaultValueHandling # 0
    Ignore : DefaultValueHandling # 1
    Populate : DefaultValueHandling # 2
    IgnoreAndPopulate : DefaultValueHandling # 3


class FloatFormatHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    String : FloatFormatHandling # 0
    Symbol : FloatFormatHandling # 1
    DefaultValue : FloatFormatHandling # 2


class FloatParseHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Double : FloatParseHandling # 0
    Decimal : FloatParseHandling # 1


class Formatting(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : Formatting # 0
    Indented : Formatting # 1


class IArrayPool_GenericClasses(abc.ABCMeta):
    Generic_IArrayPool_GenericClasses_IArrayPool_1_T = typing.TypeVar('Generic_IArrayPool_GenericClasses_IArrayPool_1_T')
    def __getitem__(self, types : typing.Type[Generic_IArrayPool_GenericClasses_IArrayPool_1_T]) -> typing.Type[IArrayPool_1[Generic_IArrayPool_GenericClasses_IArrayPool_1_T]]: ...

IArrayPool : IArrayPool_GenericClasses

IArrayPool_1_T = typing.TypeVar('IArrayPool_1_T')
class IArrayPool_1(typing.Generic[IArrayPool_1_T], typing.Protocol):
    @abc.abstractmethod
    def Rent(self, minimumLength: int) -> Array_1[IArrayPool_1_T]: ...
    @abc.abstractmethod
    def Return(self, array: Array_1[IArrayPool_1_T]) -> None: ...


class IJsonLineInfo(typing.Protocol):
    @property
    def LineNumber(self) -> int: ...
    @property
    def LinePosition(self) -> int: ...
    @abc.abstractmethod
    def HasLineInfo(self) -> bool: ...


class JsonArrayAttribute(JsonContainerAttribute):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, allowNullItems: bool) -> None: ...
    @typing.overload
    def __init__(self, id: str) -> None: ...
    @property
    def AllowNullItems(self) -> bool: ...
    @AllowNullItems.setter
    def AllowNullItems(self, value: bool) -> bool: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> str: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> bool: ...
    @property
    def ItemConverterParameters(self) -> Array_1[typing.Any]: ...
    @ItemConverterParameters.setter
    def ItemConverterParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def ItemConverterType(self) -> typing.Type[typing.Any]: ...
    @ItemConverterType.setter
    def ItemConverterType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ItemIsReference(self) -> bool: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: bool) -> bool: ...
    @property
    def ItemReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ItemTypeNameHandling(self) -> TypeNameHandling: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    @property
    def NamingStrategyParameters(self) -> Array_1[typing.Any]: ...
    @NamingStrategyParameters.setter
    def NamingStrategyParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def NamingStrategyType(self) -> typing.Type[typing.Any]: ...
    @NamingStrategyType.setter
    def NamingStrategyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonConstructorAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonContainerAttribute(Attribute):
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> str: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> bool: ...
    @property
    def ItemConverterParameters(self) -> Array_1[typing.Any]: ...
    @ItemConverterParameters.setter
    def ItemConverterParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def ItemConverterType(self) -> typing.Type[typing.Any]: ...
    @ItemConverterType.setter
    def ItemConverterType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ItemIsReference(self) -> bool: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: bool) -> bool: ...
    @property
    def ItemReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ItemTypeNameHandling(self) -> TypeNameHandling: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    @property
    def NamingStrategyParameters(self) -> Array_1[typing.Any]: ...
    @NamingStrategyParameters.setter
    def NamingStrategyParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def NamingStrategyType(self) -> typing.Type[typing.Any]: ...
    @NamingStrategyType.setter
    def NamingStrategyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonConvert(abc.ABC):
    False : str
    NaN : str
    NegativeInfinity : str
    Null : str
    PositiveInfinity : str
    True : str
    Undefined : str
    @classmethod
    @property
    def DefaultSettings(cls) -> Func_1[JsonSerializerSettings]: ...
    @classmethod
    @DefaultSettings.setter
    def DefaultSettings(cls, value: Func_1[JsonSerializerSettings]) -> Func_1[JsonSerializerSettings]: ...
    # Skipped DeserializeAnonymousType due to it being static, abstract and generic.

    DeserializeAnonymousType : DeserializeAnonymousType_MethodGroup
    class DeserializeAnonymousType_MethodGroup:
        def __getitem__(self, t:typing.Type[DeserializeAnonymousType_1_T1]) -> DeserializeAnonymousType_1[DeserializeAnonymousType_1_T1]: ...

        DeserializeAnonymousType_1_T1 = typing.TypeVar('DeserializeAnonymousType_1_T1')
        class DeserializeAnonymousType_1(typing.Generic[DeserializeAnonymousType_1_T1]):
            DeserializeAnonymousType_1_T = JsonConvert.DeserializeAnonymousType_MethodGroup.DeserializeAnonymousType_1_T1
            @typing.overload
            def __call__(self, value: str, anonymousTypeObject: DeserializeAnonymousType_1_T) -> DeserializeAnonymousType_1_T:...
            @typing.overload
            def __call__(self, value: str, anonymousTypeObject: DeserializeAnonymousType_1_T, settings: JsonSerializerSettings) -> DeserializeAnonymousType_1_T:...


    # Skipped DeserializeObject due to it being static, abstract and generic.

    DeserializeObject : DeserializeObject_MethodGroup
    class DeserializeObject_MethodGroup:
        def __getitem__(self, t:typing.Type[DeserializeObject_1_T1]) -> DeserializeObject_1[DeserializeObject_1_T1]: ...

        DeserializeObject_1_T1 = typing.TypeVar('DeserializeObject_1_T1')
        class DeserializeObject_1(typing.Generic[DeserializeObject_1_T1]):
            DeserializeObject_1_T = JsonConvert.DeserializeObject_MethodGroup.DeserializeObject_1_T1
            @typing.overload
            def __call__(self, value: str) -> DeserializeObject_1_T:...
            @typing.overload
            def __call__(self, value: str, converters: Array_1[JsonConverter]) -> DeserializeObject_1_T:...
            @typing.overload
            def __call__(self, value: str, settings: JsonSerializerSettings) -> DeserializeObject_1_T:...

        @typing.overload
        def __call__(self, value: str) -> typing.Any:...
        @typing.overload
        def __call__(self, value: str, type: typing.Type[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, value: str, settings: JsonSerializerSettings) -> typing.Any:...
        @typing.overload
        def __call__(self, value: str, type: typing.Type[typing.Any], converters: Array_1[JsonConverter]) -> typing.Any:...
        @typing.overload
        def __call__(self, value: str, type: typing.Type[typing.Any], settings: JsonSerializerSettings) -> typing.Any:...

    # Skipped DeserializeXmlNode due to it being static, abstract and generic.

    DeserializeXmlNode : DeserializeXmlNode_MethodGroup
    class DeserializeXmlNode_MethodGroup:
        @typing.overload
        def __call__(self, value: str) -> XmlDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str) -> XmlDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str, writeArrayAttribute: bool) -> XmlDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str, writeArrayAttribute: bool, encodeSpecialCharacters: bool) -> XmlDocument:...

    # Skipped DeserializeXNode due to it being static, abstract and generic.

    DeserializeXNode : DeserializeXNode_MethodGroup
    class DeserializeXNode_MethodGroup:
        @typing.overload
        def __call__(self, value: str) -> XDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str) -> XDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str, writeArrayAttribute: bool) -> XDocument:...
        @typing.overload
        def __call__(self, value: str, deserializeRootElementName: str, writeArrayAttribute: bool, encodeSpecialCharacters: bool) -> XDocument:...

    # Skipped PopulateObject due to it being static, abstract and generic.

    PopulateObject : PopulateObject_MethodGroup
    class PopulateObject_MethodGroup:
        @typing.overload
        def __call__(self, value: str, target: typing.Any) -> None:...
        @typing.overload
        def __call__(self, value: str, target: typing.Any, settings: JsonSerializerSettings) -> None:...

    # Skipped SerializeObject due to it being static, abstract and generic.

    SerializeObject : SerializeObject_MethodGroup
    class SerializeObject_MethodGroup:
        @typing.overload
        def __call__(self, value: typing.Any) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, converters: Array_1[JsonConverter]) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, formatting: Formatting) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, settings: JsonSerializerSettings) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, formatting: Formatting, converters: Array_1[JsonConverter]) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, formatting: Formatting, settings: JsonSerializerSettings) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, type: typing.Type[typing.Any], settings: JsonSerializerSettings) -> str:...
        @typing.overload
        def __call__(self, value: typing.Any, type: typing.Type[typing.Any], formatting: Formatting, settings: JsonSerializerSettings) -> str:...

    # Skipped SerializeXmlNode due to it being static, abstract and generic.

    SerializeXmlNode : SerializeXmlNode_MethodGroup
    class SerializeXmlNode_MethodGroup:
        @typing.overload
        def __call__(self, node: XmlNode) -> str:...
        @typing.overload
        def __call__(self, node: XmlNode, formatting: Formatting) -> str:...
        @typing.overload
        def __call__(self, node: XmlNode, formatting: Formatting, omitRootObject: bool) -> str:...

    # Skipped SerializeXNode due to it being static, abstract and generic.

    SerializeXNode : SerializeXNode_MethodGroup
    class SerializeXNode_MethodGroup:
        @typing.overload
        def __call__(self, node: XObject) -> str:...
        @typing.overload
        def __call__(self, node: XObject, formatting: Formatting) -> str:...
        @typing.overload
        def __call__(self, node: XObject, formatting: Formatting, omitRootObject: bool) -> str:...

    # Skipped ToString due to it being static, abstract and generic.

    ToString : ToString_MethodGroup
    class ToString_MethodGroup:
        @typing.overload
        def __call__(self, value: float) -> str:...
        # Method ToString(value : Double) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str) -> str:...
        # Method ToString(value : Int32) was skipped since it collides with above method
        # Method ToString(value : Int16) was skipped since it collides with above method
        # Method ToString(value : UInt16) was skipped since it collides with above method
        # Method ToString(value : UInt32) was skipped since it collides with above method
        # Method ToString(value : Int64) was skipped since it collides with above method
        # Method ToString(value : UInt64) was skipped since it collides with above method
        # Method ToString(value : Byte) was skipped since it collides with above method
        # Method ToString(value : SByte) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal) -> str:...
        @typing.overload
        def __call__(self, value: DateTime) -> str:...
        @typing.overload
        def __call__(self, value: DateTimeOffset) -> str:...
        # Method ToString(value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Enum) -> str:...
        @typing.overload
        def __call__(self, value: Guid) -> str:...
        @typing.overload
        def __call__(self, value: TimeSpan) -> str:...
        @typing.overload
        def __call__(self, value: Uri) -> str:...
        # Method ToString(value : String) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Any) -> str:...
        @typing.overload
        def __call__(self, value: str, delimiter: str) -> str:...
        @typing.overload
        def __call__(self, value: DateTimeOffset, format: DateFormatHandling) -> str:...
        @typing.overload
        def __call__(self, value: str, delimiter: str, stringEscapeHandling: StringEscapeHandling) -> str:...
        @typing.overload
        def __call__(self, value: DateTime, format: DateFormatHandling, timeZoneHandling: DateTimeZoneHandling) -> str:...



class JsonConverter_GenericClasses(abc.ABCMeta):
    Generic_JsonConverter_GenericClasses_JsonConverter_1_T = typing.TypeVar('Generic_JsonConverter_GenericClasses_JsonConverter_1_T')
    def __getitem__(self, types : typing.Type[Generic_JsonConverter_GenericClasses_JsonConverter_1_T]) -> typing.Type[JsonConverter_1[Generic_JsonConverter_GenericClasses_JsonConverter_1_T]]: ...

class JsonConverter(JsonConverter_0, metaclass =JsonConverter_GenericClasses): ...

class JsonConverter_0(abc.ABC):
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @abc.abstractmethod
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    @abc.abstractmethod
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    @abc.abstractmethod
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


JsonConverter_1_T = typing.TypeVar('JsonConverter_1_T')
class JsonConverter_1(typing.Generic[JsonConverter_1_T], JsonConverter_0):
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    # Skipped ReadJson due to it being static, abstract and generic.

    ReadJson : ReadJson_MethodGroup[JsonConverter_1_T]
    ReadJson_MethodGroup_JsonConverter_1_T = typing.TypeVar('ReadJson_MethodGroup_JsonConverter_1_T')
    class ReadJson_MethodGroup(typing.Generic[ReadJson_MethodGroup_JsonConverter_1_T]):
        ReadJson_MethodGroup_JsonConverter_1_T = JsonConverter_1.ReadJson_MethodGroup_JsonConverter_1_T
        @typing.overload
        def __call__(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any:...
        @typing.overload
        def __call__(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: ReadJson_MethodGroup_JsonConverter_1_T, hasExistingValue: bool, serializer: JsonSerializer) -> ReadJson_MethodGroup_JsonConverter_1_T:...

    # Skipped WriteJson due to it being static, abstract and generic.

    WriteJson : WriteJson_MethodGroup[JsonConverter_1_T]
    WriteJson_MethodGroup_JsonConverter_1_T = typing.TypeVar('WriteJson_MethodGroup_JsonConverter_1_T')
    class WriteJson_MethodGroup(typing.Generic[WriteJson_MethodGroup_JsonConverter_1_T]):
        WriteJson_MethodGroup_JsonConverter_1_T = JsonConverter_1.WriteJson_MethodGroup_JsonConverter_1_T
        @typing.overload
        def __call__(self, writer: JsonWriter, value: WriteJson_MethodGroup_JsonConverter_1_T, serializer: JsonSerializer) -> None:...
        @typing.overload
        def __call__(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None:...



class JsonConverterAttribute(Attribute):
    @typing.overload
    def __init__(self, converterType: typing.Type[typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, converterType: typing.Type[typing.Any], converterParameters: Array_1[typing.Any]) -> None: ...
    @property
    def ConverterParameters(self) -> Array_1[typing.Any]: ...
    @property
    def ConverterType(self) -> typing.Type[typing.Any]: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonConverterCollection(Collection_1[JsonConverter]):
    def __init__(self) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self) -> JsonConverter: ...
    @Item.setter
    def Item(self, value: JsonConverter) -> JsonConverter: ...


class JsonDictionaryAttribute(JsonContainerAttribute):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, id: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> str: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> bool: ...
    @property
    def ItemConverterParameters(self) -> Array_1[typing.Any]: ...
    @ItemConverterParameters.setter
    def ItemConverterParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def ItemConverterType(self) -> typing.Type[typing.Any]: ...
    @ItemConverterType.setter
    def ItemConverterType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ItemIsReference(self) -> bool: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: bool) -> bool: ...
    @property
    def ItemReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ItemTypeNameHandling(self) -> TypeNameHandling: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    @property
    def NamingStrategyParameters(self) -> Array_1[typing.Any]: ...
    @NamingStrategyParameters.setter
    def NamingStrategyParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def NamingStrategyType(self) -> typing.Type[typing.Any]: ...
    @NamingStrategyType.setter
    def NamingStrategyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonException(Exception):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class JsonExtensionDataAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def ReadData(self) -> bool: ...
    @ReadData.setter
    def ReadData(self, value: bool) -> bool: ...
    @property
    def TypeId(self) -> typing.Any: ...
    @property
    def WriteData(self) -> bool: ...
    @WriteData.setter
    def WriteData(self, value: bool) -> bool: ...


class JsonIgnoreAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonNameTable(abc.ABC):
    @abc.abstractmethod
    def Get(self, key: Array_1[str], start: int, length: int) -> str: ...


class JsonObjectAttribute(JsonContainerAttribute):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, id: str) -> None: ...
    @typing.overload
    def __init__(self, memberSerialization: MemberSerialization) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> str: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> str: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> bool: ...
    @property
    def ItemConverterParameters(self) -> Array_1[typing.Any]: ...
    @ItemConverterParameters.setter
    def ItemConverterParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def ItemConverterType(self) -> typing.Type[typing.Any]: ...
    @ItemConverterType.setter
    def ItemConverterType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ItemIsReference(self) -> bool: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: bool) -> bool: ...
    @property
    def ItemNullValueHandling(self) -> NullValueHandling: ...
    @ItemNullValueHandling.setter
    def ItemNullValueHandling(self, value: NullValueHandling) -> NullValueHandling: ...
    @property
    def ItemReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ItemRequired(self) -> Required: ...
    @ItemRequired.setter
    def ItemRequired(self, value: Required) -> Required: ...
    @property
    def ItemTypeNameHandling(self) -> TypeNameHandling: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    @property
    def MemberSerialization(self) -> MemberSerialization: ...
    @MemberSerialization.setter
    def MemberSerialization(self, value: MemberSerialization) -> MemberSerialization: ...
    @property
    def MissingMemberHandling(self) -> MissingMemberHandling: ...
    @MissingMemberHandling.setter
    def MissingMemberHandling(self, value: MissingMemberHandling) -> MissingMemberHandling: ...
    @property
    def NamingStrategyParameters(self) -> Array_1[typing.Any]: ...
    @NamingStrategyParameters.setter
    def NamingStrategyParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def NamingStrategyType(self) -> typing.Type[typing.Any]: ...
    @NamingStrategyType.setter
    def NamingStrategyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonPropertyAttribute(Attribute):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, propertyName: str) -> None: ...
    @property
    def DefaultValueHandling(self) -> DefaultValueHandling: ...
    @DefaultValueHandling.setter
    def DefaultValueHandling(self, value: DefaultValueHandling) -> DefaultValueHandling: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> bool: ...
    @property
    def ItemConverterParameters(self) -> Array_1[typing.Any]: ...
    @ItemConverterParameters.setter
    def ItemConverterParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def ItemConverterType(self) -> typing.Type[typing.Any]: ...
    @ItemConverterType.setter
    def ItemConverterType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def ItemIsReference(self) -> bool: ...
    @ItemIsReference.setter
    def ItemIsReference(self, value: bool) -> bool: ...
    @property
    def ItemReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ItemReferenceLoopHandling.setter
    def ItemReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ItemTypeNameHandling(self) -> TypeNameHandling: ...
    @ItemTypeNameHandling.setter
    def ItemTypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    @property
    def NamingStrategyParameters(self) -> Array_1[typing.Any]: ...
    @NamingStrategyParameters.setter
    def NamingStrategyParameters(self, value: Array_1[typing.Any]) -> Array_1[typing.Any]: ...
    @property
    def NamingStrategyType(self) -> typing.Type[typing.Any]: ...
    @NamingStrategyType.setter
    def NamingStrategyType(self, value: typing.Type[typing.Any]) -> typing.Type[typing.Any]: ...
    @property
    def NullValueHandling(self) -> NullValueHandling: ...
    @NullValueHandling.setter
    def NullValueHandling(self, value: NullValueHandling) -> NullValueHandling: ...
    @property
    def ObjectCreationHandling(self) -> ObjectCreationHandling: ...
    @ObjectCreationHandling.setter
    def ObjectCreationHandling(self, value: ObjectCreationHandling) -> ObjectCreationHandling: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> int: ...
    @property
    def PropertyName(self) -> str: ...
    @PropertyName.setter
    def PropertyName(self, value: str) -> str: ...
    @property
    def ReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ReferenceLoopHandling.setter
    def ReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def Required(self) -> Required: ...
    @Required.setter
    def Required(self, value: Required) -> Required: ...
    @property
    def TypeId(self) -> typing.Any: ...
    @property
    def TypeNameHandling(self) -> TypeNameHandling: ...
    @TypeNameHandling.setter
    def TypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...


class JsonReader(IDisposable, IAsyncDisposable, abc.ABC):
    @property
    def CloseInput(self) -> bool: ...
    @CloseInput.setter
    def CloseInput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def Depth(self) -> int: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def Path(self) -> str: ...
    @property
    def QuoteChar(self) -> str: ...
    @QuoteChar.setter
    def QuoteChar(self, value: str) -> str: ...
    @property
    def SupportMultipleContent(self) -> bool: ...
    @SupportMultipleContent.setter
    def SupportMultipleContent(self, value: bool) -> bool: ...
    @property
    def TokenType(self) -> JsonToken: ...
    @property
    def Value(self) -> typing.Any: ...
    @property
    def ValueType(self) -> typing.Type[typing.Any]: ...
    def Close(self) -> None: ...
    @abc.abstractmethod
    def Read(self) -> bool: ...
    def ReadAsBoolean(self) -> typing.Optional[bool]: ...
    def ReadAsBooleanAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[bool]]: ...
    def ReadAsBytes(self) -> Array_1[int]: ...
    def ReadAsBytesAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[Array_1[int]]: ...
    def ReadAsDateTime(self) -> typing.Optional[DateTime]: ...
    def ReadAsDateTimeAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[DateTime]]: ...
    def ReadAsDateTimeOffset(self) -> typing.Optional[DateTimeOffset]: ...
    def ReadAsDateTimeOffsetAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[DateTimeOffset]]: ...
    def ReadAsDecimal(self) -> typing.Optional[Decimal]: ...
    def ReadAsDecimalAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[Decimal]]: ...
    def ReadAsDouble(self) -> typing.Optional[float]: ...
    def ReadAsDoubleAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[float]]: ...
    def ReadAsInt32(self) -> typing.Optional[int]: ...
    def ReadAsInt32Async(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[int]]: ...
    def ReadAsString(self) -> str: ...
    def ReadAsStringAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[str]: ...
    def ReadAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[bool]: ...
    def Skip(self) -> None: ...
    def SkipAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...


class JsonReaderException(JsonException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @typing.overload
    def __init__(self, message: str, path: str, lineNumber: int, linePosition: int, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def LineNumber(self) -> int: ...
    @property
    def LinePosition(self) -> int: ...
    @property
    def Message(self) -> str: ...
    @property
    def Path(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class JsonRequiredAttribute(Attribute):
    def __init__(self) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...


class JsonSerializationException(JsonException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @typing.overload
    def __init__(self, message: str, path: str, lineNumber: int, linePosition: int, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def LineNumber(self) -> int: ...
    @property
    def LinePosition(self) -> int: ...
    @property
    def Message(self) -> str: ...
    @property
    def Path(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class JsonSerializer:
    def __init__(self) -> None: ...
    @property
    def Binder(self) -> SerializationBinder: ...
    @Binder.setter
    def Binder(self, value: SerializationBinder) -> SerializationBinder: ...
    @property
    def CheckAdditionalContent(self) -> bool: ...
    @CheckAdditionalContent.setter
    def CheckAdditionalContent(self, value: bool) -> bool: ...
    @property
    def ConstructorHandling(self) -> ConstructorHandling: ...
    @ConstructorHandling.setter
    def ConstructorHandling(self, value: ConstructorHandling) -> ConstructorHandling: ...
    @property
    def Context(self) -> StreamingContext: ...
    @Context.setter
    def Context(self, value: StreamingContext) -> StreamingContext: ...
    @property
    def ContractResolver(self) -> IContractResolver: ...
    @ContractResolver.setter
    def ContractResolver(self, value: IContractResolver) -> IContractResolver: ...
    @property
    def Converters(self) -> JsonConverterCollection: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatHandling(self) -> DateFormatHandling: ...
    @DateFormatHandling.setter
    def DateFormatHandling(self, value: DateFormatHandling) -> DateFormatHandling: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def DefaultValueHandling(self) -> DefaultValueHandling: ...
    @DefaultValueHandling.setter
    def DefaultValueHandling(self, value: DefaultValueHandling) -> DefaultValueHandling: ...
    @property
    def EqualityComparer(self) -> IEqualityComparer: ...
    @EqualityComparer.setter
    def EqualityComparer(self, value: IEqualityComparer) -> IEqualityComparer: ...
    @property
    def FloatFormatHandling(self) -> FloatFormatHandling: ...
    @FloatFormatHandling.setter
    def FloatFormatHandling(self, value: FloatFormatHandling) -> FloatFormatHandling: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def Formatting(self) -> Formatting: ...
    @Formatting.setter
    def Formatting(self, value: Formatting) -> Formatting: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def MetadataPropertyHandling(self) -> MetadataPropertyHandling: ...
    @MetadataPropertyHandling.setter
    def MetadataPropertyHandling(self, value: MetadataPropertyHandling) -> MetadataPropertyHandling: ...
    @property
    def MissingMemberHandling(self) -> MissingMemberHandling: ...
    @MissingMemberHandling.setter
    def MissingMemberHandling(self, value: MissingMemberHandling) -> MissingMemberHandling: ...
    @property
    def NullValueHandling(self) -> NullValueHandling: ...
    @NullValueHandling.setter
    def NullValueHandling(self, value: NullValueHandling) -> NullValueHandling: ...
    @property
    def ObjectCreationHandling(self) -> ObjectCreationHandling: ...
    @ObjectCreationHandling.setter
    def ObjectCreationHandling(self, value: ObjectCreationHandling) -> ObjectCreationHandling: ...
    @property
    def PreserveReferencesHandling(self) -> PreserveReferencesHandling: ...
    @PreserveReferencesHandling.setter
    def PreserveReferencesHandling(self, value: PreserveReferencesHandling) -> PreserveReferencesHandling: ...
    @property
    def ReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ReferenceLoopHandling.setter
    def ReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ReferenceResolver(self) -> IReferenceResolver: ...
    @ReferenceResolver.setter
    def ReferenceResolver(self, value: IReferenceResolver) -> IReferenceResolver: ...
    @property
    def SerializationBinder(self) -> ISerializationBinder: ...
    @SerializationBinder.setter
    def SerializationBinder(self, value: ISerializationBinder) -> ISerializationBinder: ...
    @property
    def StringEscapeHandling(self) -> StringEscapeHandling: ...
    @StringEscapeHandling.setter
    def StringEscapeHandling(self, value: StringEscapeHandling) -> StringEscapeHandling: ...
    @property
    def TraceWriter(self) -> ITraceWriter: ...
    @TraceWriter.setter
    def TraceWriter(self, value: ITraceWriter) -> ITraceWriter: ...
    @property
    def TypeNameAssemblyFormat(self) -> FormatterAssemblyStyle: ...
    @TypeNameAssemblyFormat.setter
    def TypeNameAssemblyFormat(self, value: FormatterAssemblyStyle) -> FormatterAssemblyStyle: ...
    @property
    def TypeNameAssemblyFormatHandling(self) -> TypeNameAssemblyFormatHandling: ...
    @TypeNameAssemblyFormatHandling.setter
    def TypeNameAssemblyFormatHandling(self, value: TypeNameAssemblyFormatHandling) -> TypeNameAssemblyFormatHandling: ...
    @property
    def TypeNameHandling(self) -> TypeNameHandling: ...
    @TypeNameHandling.setter
    def TypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self) -> JsonSerializer:...
        @typing.overload
        def __call__(self, settings: JsonSerializerSettings) -> JsonSerializer:...

    # Skipped CreateDefault due to it being static, abstract and generic.

    CreateDefault : CreateDefault_MethodGroup
    class CreateDefault_MethodGroup:
        @typing.overload
        def __call__(self) -> JsonSerializer:...
        @typing.overload
        def __call__(self, settings: JsonSerializerSettings) -> JsonSerializer:...

    # Skipped Deserialize due to it being static, abstract and generic.

    Deserialize : Deserialize_MethodGroup
    class Deserialize_MethodGroup:
        def __getitem__(self, t:typing.Type[Deserialize_1_T1]) -> Deserialize_1[Deserialize_1_T1]: ...

        Deserialize_1_T1 = typing.TypeVar('Deserialize_1_T1')
        class Deserialize_1(typing.Generic[Deserialize_1_T1]):
            Deserialize_1_T = JsonSerializer.Deserialize_MethodGroup.Deserialize_1_T1
            def __call__(self, reader: JsonReader) -> Deserialize_1_T:...

        @typing.overload
        def __call__(self, reader: JsonReader) -> typing.Any:...
        @typing.overload
        def __call__(self, reader: TextReader, objectType: typing.Type[typing.Any]) -> typing.Any:...
        @typing.overload
        def __call__(self, reader: JsonReader, objectType: typing.Type[typing.Any]) -> typing.Any:...

    # Skipped Populate due to it being static, abstract and generic.

    Populate : Populate_MethodGroup
    class Populate_MethodGroup:
        @typing.overload
        def __call__(self, reader: TextReader, target: typing.Any) -> None:...
        @typing.overload
        def __call__(self, reader: JsonReader, target: typing.Any) -> None:...

    # Skipped Serialize due to it being static, abstract and generic.

    Serialize : Serialize_MethodGroup
    class Serialize_MethodGroup:
        @typing.overload
        def __call__(self, textWriter: TextWriter, value: typing.Any) -> None:...
        @typing.overload
        def __call__(self, jsonWriter: JsonWriter, value: typing.Any) -> None:...
        @typing.overload
        def __call__(self, textWriter: TextWriter, value: typing.Any, objectType: typing.Type[typing.Any]) -> None:...
        @typing.overload
        def __call__(self, jsonWriter: JsonWriter, value: typing.Any, objectType: typing.Type[typing.Any]) -> None:...



class JsonSerializerSettings:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, original: JsonSerializerSettings) -> None: ...
    @property
    def Binder(self) -> SerializationBinder: ...
    @Binder.setter
    def Binder(self, value: SerializationBinder) -> SerializationBinder: ...
    @property
    def CheckAdditionalContent(self) -> bool: ...
    @CheckAdditionalContent.setter
    def CheckAdditionalContent(self, value: bool) -> bool: ...
    @property
    def ConstructorHandling(self) -> ConstructorHandling: ...
    @ConstructorHandling.setter
    def ConstructorHandling(self, value: ConstructorHandling) -> ConstructorHandling: ...
    @property
    def Context(self) -> StreamingContext: ...
    @Context.setter
    def Context(self, value: StreamingContext) -> StreamingContext: ...
    @property
    def ContractResolver(self) -> IContractResolver: ...
    @ContractResolver.setter
    def ContractResolver(self, value: IContractResolver) -> IContractResolver: ...
    @property
    def Converters(self) -> IList_1[JsonConverter]: ...
    @Converters.setter
    def Converters(self, value: IList_1[JsonConverter]) -> IList_1[JsonConverter]: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatHandling(self) -> DateFormatHandling: ...
    @DateFormatHandling.setter
    def DateFormatHandling(self, value: DateFormatHandling) -> DateFormatHandling: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def DefaultValueHandling(self) -> DefaultValueHandling: ...
    @DefaultValueHandling.setter
    def DefaultValueHandling(self, value: DefaultValueHandling) -> DefaultValueHandling: ...
    @property
    def EqualityComparer(self) -> IEqualityComparer: ...
    @EqualityComparer.setter
    def EqualityComparer(self, value: IEqualityComparer) -> IEqualityComparer: ...
    @property
    def Error(self) -> EventHandler_1[ErrorEventArgs]: ...
    @Error.setter
    def Error(self, value: EventHandler_1[ErrorEventArgs]) -> EventHandler_1[ErrorEventArgs]: ...
    @property
    def FloatFormatHandling(self) -> FloatFormatHandling: ...
    @FloatFormatHandling.setter
    def FloatFormatHandling(self, value: FloatFormatHandling) -> FloatFormatHandling: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def Formatting(self) -> Formatting: ...
    @Formatting.setter
    def Formatting(self, value: Formatting) -> Formatting: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def MetadataPropertyHandling(self) -> MetadataPropertyHandling: ...
    @MetadataPropertyHandling.setter
    def MetadataPropertyHandling(self, value: MetadataPropertyHandling) -> MetadataPropertyHandling: ...
    @property
    def MissingMemberHandling(self) -> MissingMemberHandling: ...
    @MissingMemberHandling.setter
    def MissingMemberHandling(self, value: MissingMemberHandling) -> MissingMemberHandling: ...
    @property
    def NullValueHandling(self) -> NullValueHandling: ...
    @NullValueHandling.setter
    def NullValueHandling(self, value: NullValueHandling) -> NullValueHandling: ...
    @property
    def ObjectCreationHandling(self) -> ObjectCreationHandling: ...
    @ObjectCreationHandling.setter
    def ObjectCreationHandling(self, value: ObjectCreationHandling) -> ObjectCreationHandling: ...
    @property
    def PreserveReferencesHandling(self) -> PreserveReferencesHandling: ...
    @PreserveReferencesHandling.setter
    def PreserveReferencesHandling(self, value: PreserveReferencesHandling) -> PreserveReferencesHandling: ...
    @property
    def ReferenceLoopHandling(self) -> ReferenceLoopHandling: ...
    @ReferenceLoopHandling.setter
    def ReferenceLoopHandling(self, value: ReferenceLoopHandling) -> ReferenceLoopHandling: ...
    @property
    def ReferenceResolver(self) -> IReferenceResolver: ...
    @ReferenceResolver.setter
    def ReferenceResolver(self, value: IReferenceResolver) -> IReferenceResolver: ...
    @property
    def ReferenceResolverProvider(self) -> Func_1[IReferenceResolver]: ...
    @ReferenceResolverProvider.setter
    def ReferenceResolverProvider(self, value: Func_1[IReferenceResolver]) -> Func_1[IReferenceResolver]: ...
    @property
    def SerializationBinder(self) -> ISerializationBinder: ...
    @SerializationBinder.setter
    def SerializationBinder(self, value: ISerializationBinder) -> ISerializationBinder: ...
    @property
    def StringEscapeHandling(self) -> StringEscapeHandling: ...
    @StringEscapeHandling.setter
    def StringEscapeHandling(self, value: StringEscapeHandling) -> StringEscapeHandling: ...
    @property
    def TraceWriter(self) -> ITraceWriter: ...
    @TraceWriter.setter
    def TraceWriter(self, value: ITraceWriter) -> ITraceWriter: ...
    @property
    def TypeNameAssemblyFormat(self) -> FormatterAssemblyStyle: ...
    @TypeNameAssemblyFormat.setter
    def TypeNameAssemblyFormat(self, value: FormatterAssemblyStyle) -> FormatterAssemblyStyle: ...
    @property
    def TypeNameAssemblyFormatHandling(self) -> TypeNameAssemblyFormatHandling: ...
    @TypeNameAssemblyFormatHandling.setter
    def TypeNameAssemblyFormatHandling(self, value: TypeNameAssemblyFormatHandling) -> TypeNameAssemblyFormatHandling: ...
    @property
    def TypeNameHandling(self) -> TypeNameHandling: ...
    @TypeNameHandling.setter
    def TypeNameHandling(self, value: TypeNameHandling) -> TypeNameHandling: ...


class JsonTextReader(JsonReader, IJsonLineInfo):
    def __init__(self, reader: TextReader) -> None: ...
    @property
    def ArrayPool(self) -> IArrayPool_1[str]: ...
    @ArrayPool.setter
    def ArrayPool(self, value: IArrayPool_1[str]) -> IArrayPool_1[str]: ...
    @property
    def CloseInput(self) -> bool: ...
    @CloseInput.setter
    def CloseInput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def Depth(self) -> int: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def LineNumber(self) -> int: ...
    @property
    def LinePosition(self) -> int: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def Path(self) -> str: ...
    @property
    def PropertyNameTable(self) -> JsonNameTable: ...
    @PropertyNameTable.setter
    def PropertyNameTable(self, value: JsonNameTable) -> JsonNameTable: ...
    @property
    def QuoteChar(self) -> str: ...
    @QuoteChar.setter
    def QuoteChar(self, value: str) -> str: ...
    @property
    def SupportMultipleContent(self) -> bool: ...
    @SupportMultipleContent.setter
    def SupportMultipleContent(self, value: bool) -> bool: ...
    @property
    def TokenType(self) -> JsonToken: ...
    @property
    def Value(self) -> typing.Any: ...
    @property
    def ValueType(self) -> typing.Type[typing.Any]: ...
    def Close(self) -> None: ...
    def HasLineInfo(self) -> bool: ...
    def Read(self) -> bool: ...
    def ReadAsBoolean(self) -> typing.Optional[bool]: ...
    def ReadAsBooleanAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[bool]]: ...
    def ReadAsBytes(self) -> Array_1[int]: ...
    def ReadAsBytesAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[Array_1[int]]: ...
    def ReadAsDateTime(self) -> typing.Optional[DateTime]: ...
    def ReadAsDateTimeAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[DateTime]]: ...
    def ReadAsDateTimeOffset(self) -> typing.Optional[DateTimeOffset]: ...
    def ReadAsDateTimeOffsetAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[DateTimeOffset]]: ...
    def ReadAsDecimal(self) -> typing.Optional[Decimal]: ...
    def ReadAsDecimalAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[Decimal]]: ...
    def ReadAsDouble(self) -> typing.Optional[float]: ...
    def ReadAsDoubleAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[float]]: ...
    def ReadAsInt32(self) -> typing.Optional[int]: ...
    def ReadAsInt32Async(self, cancellationToken: CancellationToken = ...) -> Task_1[typing.Optional[int]]: ...
    def ReadAsString(self) -> str: ...
    def ReadAsStringAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[str]: ...
    def ReadAsync(self, cancellationToken: CancellationToken = ...) -> Task_1[bool]: ...


class JsonTextWriter(JsonWriter):
    def __init__(self, textWriter: TextWriter) -> None: ...
    @property
    def ArrayPool(self) -> IArrayPool_1[str]: ...
    @ArrayPool.setter
    def ArrayPool(self, value: IArrayPool_1[str]) -> IArrayPool_1[str]: ...
    @property
    def AutoCompleteOnClose(self) -> bool: ...
    @AutoCompleteOnClose.setter
    def AutoCompleteOnClose(self, value: bool) -> bool: ...
    @property
    def CloseOutput(self) -> bool: ...
    @CloseOutput.setter
    def CloseOutput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatHandling(self) -> DateFormatHandling: ...
    @DateFormatHandling.setter
    def DateFormatHandling(self, value: DateFormatHandling) -> DateFormatHandling: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def FloatFormatHandling(self) -> FloatFormatHandling: ...
    @FloatFormatHandling.setter
    def FloatFormatHandling(self, value: FloatFormatHandling) -> FloatFormatHandling: ...
    @property
    def Formatting(self) -> Formatting: ...
    @Formatting.setter
    def Formatting(self, value: Formatting) -> Formatting: ...
    @property
    def Indentation(self) -> int: ...
    @Indentation.setter
    def Indentation(self, value: int) -> int: ...
    @property
    def IndentChar(self) -> str: ...
    @IndentChar.setter
    def IndentChar(self, value: str) -> str: ...
    @property
    def Path(self) -> str: ...
    @property
    def QuoteChar(self) -> str: ...
    @QuoteChar.setter
    def QuoteChar(self, value: str) -> str: ...
    @property
    def QuoteName(self) -> bool: ...
    @QuoteName.setter
    def QuoteName(self, value: bool) -> bool: ...
    @property
    def StringEscapeHandling(self) -> StringEscapeHandling: ...
    @StringEscapeHandling.setter
    def StringEscapeHandling(self, value: StringEscapeHandling) -> StringEscapeHandling: ...
    @property
    def WriteState(self) -> WriteState: ...
    def Close(self) -> None: ...
    def CloseAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def Flush(self) -> None: ...
    def FlushAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteComment(self, text: str) -> None: ...
    def WriteCommentAsync(self, text: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndArrayAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndConstructorAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndObjectAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteNull(self) -> None: ...
    def WriteNullAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteRaw(self, json: str) -> None: ...
    def WriteRawAsync(self, json: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteRawValueAsync(self, json: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartArray(self) -> None: ...
    def WriteStartArrayAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartConstructor(self, name: str) -> None: ...
    def WriteStartConstructorAsync(self, name: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartObject(self) -> None: ...
    def WriteStartObjectAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteUndefined(self) -> None: ...
    def WriteUndefinedAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteWhitespace(self, ws: str) -> None: ...
    def WriteWhitespaceAsync(self, ws: str, cancellationToken: CancellationToken = ...) -> Task: ...
    # Skipped WritePropertyName due to it being static, abstract and generic.

    WritePropertyName : WritePropertyName_MethodGroup
    class WritePropertyName_MethodGroup:
        @typing.overload
        def __call__(self, name: str) -> None:...
        @typing.overload
        def __call__(self, name: str, escape: bool) -> None:...

    # Skipped WritePropertyNameAsync due to it being static, abstract and generic.

    WritePropertyNameAsync : WritePropertyNameAsync_MethodGroup
    class WritePropertyNameAsync_MethodGroup:
        @typing.overload
        def __call__(self, name: str, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, name: str, escape: bool, cancellationToken: CancellationToken = ...) -> Task:...

    # Skipped WriteValue due to it being static, abstract and generic.

    WriteValue : WriteValue_MethodGroup
    class WriteValue_MethodGroup:
        @typing.overload
        def __call__(self, value: float) -> None:...
        # Method WriteValue(value : Double) was skipped since it collides with above method
        # Method WriteValue(value : Int32) was skipped since it collides with above method
        # Method WriteValue(value : UInt32) was skipped since it collides with above method
        # Method WriteValue(value : Int64) was skipped since it collides with above method
        # Method WriteValue(value : UInt64) was skipped since it collides with above method
        # Method WriteValue(value : Int16) was skipped since it collides with above method
        # Method WriteValue(value : UInt16) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str) -> None:...
        # Method WriteValue(value : Byte) was skipped since it collides with above method
        # Method WriteValue(value : SByte) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[int]) -> None:...
        @typing.overload
        def __call__(self, value: typing.Optional[float]) -> None:...
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : String) was skipped since it collides with above method
        # Method WriteValue(value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: DateTime) -> None:...
        @typing.overload
        def __call__(self, value: DateTimeOffset) -> None:...
        @typing.overload
        def __call__(self, value: Guid) -> None:...
        @typing.overload
        def __call__(self, value: TimeSpan) -> None:...
        @typing.overload
        def __call__(self, value: Uri) -> None:...
        @typing.overload
        def __call__(self, value: typing.Any) -> None:...

    # Skipped WriteValueAsync due to it being static, abstract and generic.

    WriteValueAsync : WriteValueAsync_MethodGroup
    class WriteValueAsync_MethodGroup:
        @typing.overload
        def __call__(self, value: float, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Single, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Byte, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Int32, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Int64, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : SByte, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Int16, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt32, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt64, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt16, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Array_1[int], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[float], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[str], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[Decimal], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[DateTime], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[DateTimeOffset], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[Guid], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[TimeSpan], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Boolean, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: DateTime, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: DateTimeOffset, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Guid, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : String, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: TimeSpan, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Uri, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Any, cancellationToken: CancellationToken = ...) -> Task:...



class JsonToken(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : JsonToken # 0
    StartObject : JsonToken # 1
    StartArray : JsonToken # 2
    StartConstructor : JsonToken # 3
    PropertyName : JsonToken # 4
    Comment : JsonToken # 5
    Raw : JsonToken # 6
    Integer : JsonToken # 7
    Float : JsonToken # 8
    String : JsonToken # 9
    Boolean : JsonToken # 10
    Null : JsonToken # 11
    Undefined : JsonToken # 12
    EndObject : JsonToken # 13
    EndArray : JsonToken # 14
    EndConstructor : JsonToken # 15
    Date : JsonToken # 16
    Bytes : JsonToken # 17


class JsonValidatingReader(JsonReader, IJsonLineInfo):
    def __init__(self, reader: JsonReader) -> None: ...
    @property
    def CloseInput(self) -> bool: ...
    @CloseInput.setter
    def CloseInput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateParseHandling(self) -> DateParseHandling: ...
    @DateParseHandling.setter
    def DateParseHandling(self, value: DateParseHandling) -> DateParseHandling: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def Depth(self) -> int: ...
    @property
    def FloatParseHandling(self) -> FloatParseHandling: ...
    @FloatParseHandling.setter
    def FloatParseHandling(self, value: FloatParseHandling) -> FloatParseHandling: ...
    @property
    def MaxDepth(self) -> typing.Optional[int]: ...
    @MaxDepth.setter
    def MaxDepth(self, value: typing.Optional[int]) -> typing.Optional[int]: ...
    @property
    def Path(self) -> str: ...
    @property
    def QuoteChar(self) -> str: ...
    @QuoteChar.setter
    def QuoteChar(self, value: str) -> str: ...
    @property
    def Reader(self) -> JsonReader: ...
    @property
    def Schema(self) -> JsonSchema: ...
    @Schema.setter
    def Schema(self, value: JsonSchema) -> JsonSchema: ...
    @property
    def SupportMultipleContent(self) -> bool: ...
    @SupportMultipleContent.setter
    def SupportMultipleContent(self, value: bool) -> bool: ...
    @property
    def TokenType(self) -> JsonToken: ...
    @property
    def Value(self) -> typing.Any: ...
    @property
    def ValueType(self) -> typing.Type[typing.Any]: ...
    def Close(self) -> None: ...
    def Read(self) -> bool: ...
    def ReadAsBoolean(self) -> typing.Optional[bool]: ...
    def ReadAsBytes(self) -> Array_1[int]: ...
    def ReadAsDateTime(self) -> typing.Optional[DateTime]: ...
    def ReadAsDateTimeOffset(self) -> typing.Optional[DateTimeOffset]: ...
    def ReadAsDecimal(self) -> typing.Optional[Decimal]: ...
    def ReadAsDouble(self) -> typing.Optional[float]: ...
    def ReadAsInt32(self) -> typing.Optional[int]: ...
    def ReadAsString(self) -> str: ...


class JsonWriter(IDisposable, IAsyncDisposable, abc.ABC):
    @property
    def AutoCompleteOnClose(self) -> bool: ...
    @AutoCompleteOnClose.setter
    def AutoCompleteOnClose(self, value: bool) -> bool: ...
    @property
    def CloseOutput(self) -> bool: ...
    @CloseOutput.setter
    def CloseOutput(self, value: bool) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateFormatHandling(self) -> DateFormatHandling: ...
    @DateFormatHandling.setter
    def DateFormatHandling(self, value: DateFormatHandling) -> DateFormatHandling: ...
    @property
    def DateFormatString(self) -> str: ...
    @DateFormatString.setter
    def DateFormatString(self, value: str) -> str: ...
    @property
    def DateTimeZoneHandling(self) -> DateTimeZoneHandling: ...
    @DateTimeZoneHandling.setter
    def DateTimeZoneHandling(self, value: DateTimeZoneHandling) -> DateTimeZoneHandling: ...
    @property
    def FloatFormatHandling(self) -> FloatFormatHandling: ...
    @FloatFormatHandling.setter
    def FloatFormatHandling(self, value: FloatFormatHandling) -> FloatFormatHandling: ...
    @property
    def Formatting(self) -> Formatting: ...
    @Formatting.setter
    def Formatting(self, value: Formatting) -> Formatting: ...
    @property
    def Path(self) -> str: ...
    @property
    def StringEscapeHandling(self) -> StringEscapeHandling: ...
    @StringEscapeHandling.setter
    def StringEscapeHandling(self, value: StringEscapeHandling) -> StringEscapeHandling: ...
    @property
    def WriteState(self) -> WriteState: ...
    def Close(self) -> None: ...
    def CloseAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    @abc.abstractmethod
    def Flush(self) -> None: ...
    def FlushAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteComment(self, text: str) -> None: ...
    def WriteCommentAsync(self, text: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEnd(self) -> None: ...
    def WriteEndArray(self) -> None: ...
    def WriteEndArrayAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndConstructor(self) -> None: ...
    def WriteEndConstructorAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteEndObject(self) -> None: ...
    def WriteEndObjectAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteNull(self) -> None: ...
    def WriteNullAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteRaw(self, json: str) -> None: ...
    def WriteRawAsync(self, json: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteRawValue(self, json: str) -> None: ...
    def WriteRawValueAsync(self, json: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartArray(self) -> None: ...
    def WriteStartArrayAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartConstructor(self, name: str) -> None: ...
    def WriteStartConstructorAsync(self, name: str, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteStartObject(self) -> None: ...
    def WriteStartObjectAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteUndefined(self) -> None: ...
    def WriteUndefinedAsync(self, cancellationToken: CancellationToken = ...) -> Task: ...
    def WriteWhitespace(self, ws: str) -> None: ...
    def WriteWhitespaceAsync(self, ws: str, cancellationToken: CancellationToken = ...) -> Task: ...
    # Skipped WritePropertyName due to it being static, abstract and generic.

    WritePropertyName : WritePropertyName_MethodGroup
    class WritePropertyName_MethodGroup:
        @typing.overload
        def __call__(self, name: str) -> None:...
        @typing.overload
        def __call__(self, name: str, escape: bool) -> None:...

    # Skipped WritePropertyNameAsync due to it being static, abstract and generic.

    WritePropertyNameAsync : WritePropertyNameAsync_MethodGroup
    class WritePropertyNameAsync_MethodGroup:
        @typing.overload
        def __call__(self, name: str, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, name: str, escape: bool, cancellationToken: CancellationToken = ...) -> Task:...

    # Skipped WriteToken due to it being static, abstract and generic.

    WriteToken : WriteToken_MethodGroup
    class WriteToken_MethodGroup:
        @typing.overload
        def __call__(self, token: JsonToken) -> None:...
        @typing.overload
        def __call__(self, reader: JsonReader) -> None:...
        @typing.overload
        def __call__(self, token: JsonToken, value: typing.Any) -> None:...
        @typing.overload
        def __call__(self, reader: JsonReader, writeChildren: bool) -> None:...

    # Skipped WriteTokenAsync due to it being static, abstract and generic.

    WriteTokenAsync : WriteTokenAsync_MethodGroup
    class WriteTokenAsync_MethodGroup:
        @typing.overload
        def __call__(self, token: JsonToken, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, reader: JsonReader, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, token: JsonToken, value: typing.Any, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, reader: JsonReader, writeChildren: bool, cancellationToken: CancellationToken = ...) -> Task:...

    # Skipped WriteValue due to it being static, abstract and generic.

    WriteValue : WriteValue_MethodGroup
    class WriteValue_MethodGroup:
        @typing.overload
        def __call__(self, value: float) -> None:...
        # Method WriteValue(value : Double) was skipped since it collides with above method
        # Method WriteValue(value : Int32) was skipped since it collides with above method
        # Method WriteValue(value : UInt32) was skipped since it collides with above method
        # Method WriteValue(value : Int64) was skipped since it collides with above method
        # Method WriteValue(value : UInt64) was skipped since it collides with above method
        # Method WriteValue(value : Int16) was skipped since it collides with above method
        # Method WriteValue(value : UInt16) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str) -> None:...
        # Method WriteValue(value : Byte) was skipped since it collides with above method
        # Method WriteValue(value : SByte) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal) -> None:...
        @typing.overload
        def __call__(self, value: Array_1[int]) -> None:...
        @typing.overload
        def __call__(self, value: typing.Optional[float]) -> None:...
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[str]) -> None:...
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[Decimal]) -> None:...
        # Method WriteValue(value : Nullable`1) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[DateTime]) -> None:...
        @typing.overload
        def __call__(self, value: typing.Optional[DateTimeOffset]) -> None:...
        @typing.overload
        def __call__(self, value: typing.Optional[Guid]) -> None:...
        @typing.overload
        def __call__(self, value: typing.Optional[TimeSpan]) -> None:...
        # Method WriteValue(value : String) was skipped since it collides with above method
        # Method WriteValue(value : Boolean) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: DateTime) -> None:...
        @typing.overload
        def __call__(self, value: DateTimeOffset) -> None:...
        @typing.overload
        def __call__(self, value: Guid) -> None:...
        @typing.overload
        def __call__(self, value: TimeSpan) -> None:...
        @typing.overload
        def __call__(self, value: Uri) -> None:...
        @typing.overload
        def __call__(self, value: typing.Any) -> None:...

    # Skipped WriteValueAsync due to it being static, abstract and generic.

    WriteValueAsync : WriteValueAsync_MethodGroup
    class WriteValueAsync_MethodGroup:
        @typing.overload
        def __call__(self, value: float, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Single, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Byte, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: str, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Int32, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Int64, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : SByte, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Int16, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt32, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt64, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : UInt16, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: Decimal, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Array_1[int], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[float], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[str], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[Decimal], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Nullable`1, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: typing.Optional[DateTime], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[DateTimeOffset], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[Guid], cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Optional[TimeSpan], cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : Boolean, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: DateTime, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: DateTimeOffset, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Guid, cancellationToken: CancellationToken = ...) -> Task:...
        # Method WriteValueAsync(value : String, cancellationToken : CancellationToken) was skipped since it collides with above method
        @typing.overload
        def __call__(self, value: TimeSpan, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: Uri, cancellationToken: CancellationToken = ...) -> Task:...
        @typing.overload
        def __call__(self, value: typing.Any, cancellationToken: CancellationToken = ...) -> Task:...



class JsonWriterException(JsonException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @typing.overload
    def __init__(self, message: str) -> None: ...
    @typing.overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @typing.overload
    def __init__(self, message: str, path: str, innerException: Exception) -> None: ...
    @property
    def Data(self) -> IDictionary: ...
    @property
    def HelpLink(self) -> str: ...
    @HelpLink.setter
    def HelpLink(self, value: str) -> str: ...
    @property
    def HResult(self) -> int: ...
    @HResult.setter
    def HResult(self, value: int) -> int: ...
    @property
    def InnerException(self) -> Exception: ...
    @property
    def Message(self) -> str: ...
    @property
    def Path(self) -> str: ...
    @property
    def Source(self) -> str: ...
    @Source.setter
    def Source(self, value: str) -> str: ...
    @property
    def StackTrace(self) -> str: ...
    @property
    def TargetSite(self) -> MethodBase: ...


class MemberSerialization(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    OptOut : MemberSerialization # 0
    OptIn : MemberSerialization # 1
    Fields : MemberSerialization # 2


class MetadataPropertyHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : MetadataPropertyHandling # 0
    ReadAhead : MetadataPropertyHandling # 1
    Ignore : MetadataPropertyHandling # 2


class MissingMemberHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Ignore : MissingMemberHandling # 0
    Error : MissingMemberHandling # 1


class NullValueHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Include : NullValueHandling # 0
    Ignore : NullValueHandling # 1


class ObjectCreationHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Auto : ObjectCreationHandling # 0
    Reuse : ObjectCreationHandling # 1
    Replace : ObjectCreationHandling # 2


class PreserveReferencesHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : PreserveReferencesHandling # 0
    Objects : PreserveReferencesHandling # 1
    Arrays : PreserveReferencesHandling # 2
    All : PreserveReferencesHandling # 3


class ReferenceLoopHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Error : ReferenceLoopHandling # 0
    Ignore : ReferenceLoopHandling # 1
    Serialize : ReferenceLoopHandling # 2


class Required(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : Required # 0
    AllowNull : Required # 1
    Always : Required # 2
    DisallowNull : Required # 3


class StringEscapeHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Default : StringEscapeHandling # 0
    EscapeNonAscii : StringEscapeHandling # 1
    EscapeHtml : StringEscapeHandling # 2


class TypeNameAssemblyFormatHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Simple : TypeNameAssemblyFormatHandling # 0
    Full : TypeNameAssemblyFormatHandling # 1


class TypeNameHandling(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : TypeNameHandling # 0
    Objects : TypeNameHandling # 1
    Arrays : TypeNameHandling # 2
    All : TypeNameHandling # 3
    Auto : TypeNameHandling # 4


class WriteState(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Error : WriteState # 0
    Closed : WriteState # 1
    Object : WriteState # 2
    Array : WriteState # 3
    Constructor : WriteState # 4
    Property : WriteState # 5
    Start : WriteState # 6

