import typing, abc
from Newtonsoft.Json import JsonConverter, JsonReader, JsonSerializer, JsonWriter
from System.Globalization import CultureInfo, DateTimeStyles
from Newtonsoft.Json.Serialization import NamingStrategy
from System import Array_1

class BinaryConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class BsonObjectIdConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class CustomCreationConverter_GenericClasses(abc.ABCMeta):
    Generic_CustomCreationConverter_GenericClasses_CustomCreationConverter_1_T = typing.TypeVar('Generic_CustomCreationConverter_GenericClasses_CustomCreationConverter_1_T')
    def __getitem__(self, types : typing.Type[Generic_CustomCreationConverter_GenericClasses_CustomCreationConverter_1_T]) -> typing.Type[CustomCreationConverter_1[Generic_CustomCreationConverter_GenericClasses_CustomCreationConverter_1_T]]: ...

CustomCreationConverter : CustomCreationConverter_GenericClasses

CustomCreationConverter_1_T = typing.TypeVar('CustomCreationConverter_1_T')
class CustomCreationConverter_1(typing.Generic[CustomCreationConverter_1_T], JsonConverter_0):
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    @abc.abstractmethod
    def Create(self, objectType: typing.Type[typing.Any]) -> CustomCreationConverter_1_T: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class DataSetConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, valueType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class DataTableConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, valueType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class DateTimeConverterBase(JsonConverter_0):
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...


class DiscriminatedUnionConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class EntityKeyMemberConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class ExpandoObjectConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class IsoDateTimeConverter(DateTimeConverterBase):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def Culture(self) -> CultureInfo: ...
    @Culture.setter
    def Culture(self, value: CultureInfo) -> CultureInfo: ...
    @property
    def DateTimeFormat(self) -> str: ...
    @DateTimeFormat.setter
    def DateTimeFormat(self, value: str) -> str: ...
    @property
    def DateTimeStyles(self) -> DateTimeStyles: ...
    @DateTimeStyles.setter
    def DateTimeStyles(self, value: DateTimeStyles) -> DateTimeStyles: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class JavaScriptDateTimeConverter(DateTimeConverterBase):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class KeyValuePairConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class RegexConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class StringEnumConverter(JsonConverter_0):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, camelCaseText: bool) -> None: ...
    @typing.overload
    def __init__(self, namingStrategy: NamingStrategy, allowIntegerValues: bool = ...) -> None: ...
    @typing.overload
    def __init__(self, namingStrategyType: typing.Type[typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, namingStrategyType: typing.Type[typing.Any], namingStrategyParameters: Array_1[typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, namingStrategyType: typing.Type[typing.Any], namingStrategyParameters: Array_1[typing.Any], allowIntegerValues: bool) -> None: ...
    @property
    def AllowIntegerValues(self) -> bool: ...
    @AllowIntegerValues.setter
    def AllowIntegerValues(self, value: bool) -> bool: ...
    @property
    def CamelCaseText(self) -> bool: ...
    @CamelCaseText.setter
    def CamelCaseText(self, value: bool) -> bool: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def NamingStrategy(self) -> NamingStrategy: ...
    @NamingStrategy.setter
    def NamingStrategy(self, value: NamingStrategy) -> NamingStrategy: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class UnixDateTimeConverter(DateTimeConverterBase):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, allowPreEpoch: bool) -> None: ...
    @property
    def AllowPreEpoch(self) -> bool: ...
    @AllowPreEpoch.setter
    def AllowPreEpoch(self, value: bool) -> bool: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class VersionConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def CanConvert(self, objectType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...


class XmlNodeConverter(JsonConverter_0):
    def __init__(self) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def DeserializeRootElementName(self) -> str: ...
    @DeserializeRootElementName.setter
    def DeserializeRootElementName(self, value: str) -> str: ...
    @property
    def EncodeSpecialCharacters(self) -> bool: ...
    @EncodeSpecialCharacters.setter
    def EncodeSpecialCharacters(self, value: bool) -> bool: ...
    @property
    def OmitRootObject(self) -> bool: ...
    @OmitRootObject.setter
    def OmitRootObject(self, value: bool) -> bool: ...
    @property
    def WriteArrayAttribute(self) -> bool: ...
    @WriteArrayAttribute.setter
    def WriteArrayAttribute(self, value: bool) -> bool: ...
    def CanConvert(self, valueType: typing.Type[typing.Any]) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: typing.Type[typing.Any], existingValue: typing.Any, serializer: JsonSerializer) -> typing.Any: ...
    def WriteJson(self, writer: JsonWriter, value: typing.Any, serializer: JsonSerializer) -> None: ...

